### ISSUE TITLE
Creative-CA0132 

### ISSUE THREAD

**Issue by nmano** [vit9696/AppleALC#10]
I have x99 gaming g1
Creative-CA0132 
can you add this code to AppleALC.
[AppleHDA-272.51.3-Creative-CA0132_files.zip](https://github.com/vit9696/AppleALC/files/169879/AppleHDA-272.51.3-Creative-CA0132_files.zip)

**Comment by vit9696** [comment]
Hello,
Please follow the [wiki](https://github.com/vit9696/AppleALC/wiki) article, and pass me the right files for your codec in a pull request form. Thanks :)  
I have to warn you that the AppleHDAController patch, X99 needs, is not yet supported by AppleALC. For some short meanwhile you will have to use your bootloader to apply it, which will work just fine for testing reasons.

**Comment by nmano** [comment]
Hi
Just x99 patch with applehda and appleALC work together.

**Comment by nmano** [comment]
I need this too
ALC 260
http://www.insanelymac.com/forum/files/file/531-realtek-alc260-sound-with-applehdakext/

**Comment by nmano** [comment]
I don't know how to build kext.
