### ISSUE TITLE
ALC888S-VD still no sound and no audio device detection

### ISSUE THREAD

**Issue by fefaz** [vit9696/AppleALC#104]
Hello, it's surprising for me on this release. I see the ALC888S-VD mentioned here. Fortunately, mine is ALC888S-VD. So, I try this AppleALC.kext to my PC with dsdt injection. My dsdt.aml is no "hdef" there. I just add "hdef" through patch from Toleda. I use both layout id (11 and 28), but still no sound and no audio device detection. Am I do wrong step?

**Comment by vandroiy2013** [comment]
Those ALC888S-VD is ONLY for Medion PC's. Probably your codec have different node sequence....

**Comment by fefaz** [comment]
Can we make the node sequence match to this node sequence?

**Comment by vandroiy2013** [comment]
You should ask @mirone or @insanelydeepak on insanelymac.com...

**Comment by Mirone** [comment]
First, you must join
What are your specifications, for example:
-motherboard
-Processor
-etc.....
And a copy of your codec_dump + DSDT would be ideal.

**Comment by fefaz** [comment]
Here is my PC specifications:
- Motherboard: TH55 HD (H55BA107 BS)
- Processor: Intel Core i3 530 2.93 GHz
- GPU: GF210 1024M DDR2 128B (TC) CRT DVI
- RAM: Visipro 4GB DDR3 PC10600
- Audio:
  - Codec ID: 0X10EC0888
  - Codec Name: Realtek ALC888S-VD
and, I attach my dsdt.aml and codec_dump.

[DSDT+CodecDump](https://drive.google.com/file/d/0B62OECTYoZGPQ2tYY1RFVkt6dVk/view?usp=sharing)
I'm sorry, I can't attach my files here. So, I uploaded those in my GDrive. 
Thanks anyway.

**Comment by Mirone** [comment]
@fefaz, There is no Patch for HDEF in DSDT
That you send me, so I added the same
And he's using layout_id = 11 (0x0b), if need be, change it as needed.
[DSDT.aml.zip](https://github.com/vit9696/AppleALC/files/643923/DSDT.aml.zip)

**Comment by fefaz** [comment]
Thanks @Mirone. I already try boot with dsdt.aml from you. But, the problem not solved yet. I also try to change layout id to 28. But no changes. The problem is persist.
FYI: I put AppleALC.kext in /EFI/EFI/Clover/Kexts/10.12 (My PC running Sierra 10.12 (16A323)).

**Comment by fefaz** [comment]
I'm very sorry. I forgot to put AppleHDA.kext back in S/L/E.. :D 
Thanks for your help, all. Especially to @Mirone. 
Both layout id are worked. But no for front jack (line in and line out).

**Comment by Mirone** [comment]
Try Layout_id=9, this is my resources
