### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by RockJesus** [vit9696/AppleALC#105]
My notebook is samsung nt550p7c-s65 
 realtek alc269vc with 2.1 channel audio
[https://drive.google.com/file/d/0BzuDM1qbLG4rZURMUUt1aGZCY2M/view?usp=sharing](url)
Thanks :)

**Comment by vandroiy2013** [comment]
Ask @Mirone or @insanelydeepak on insanelymac forum to help you with custom resources. If it is possible to make it work provide here patched AppleHDA or resources for it and i'll add them.

Closed...
