### ISSUE TITLE
Creative CA0132 No Devices Detected

### ISSUE THREAD

**Issue by Healian** [vit9696/AppleALC#108]
Codec dump: http://pastebin.com/XDS2UMPS
System Report->Audio: http://pastebin.com/8nEtgfVH
OS Ver. 10.12
Using Vanilla AppleHDA: YES
AppleALC loaded before AppleHDA: YES
Processor: i7 4790k
Motherboard: Gigabyte G1.Sniper z97

I did the steps as mentioned on AppleALC github repo. Tested layout id 0 through 12, with only layout id 11 showing something in System Report->Audio->Intel High Definition Audio, yet nothing in devices nor in the Sound Output/Input (s). What should i do specially that my codec is supposed to be supported normally and even working with other people.

Any help will be appreciated as this is the 4th day trying to get the audio working properly.

NOTE: This is the only step remaining for a successful hackintosh on my PC, if audio works i will post all links and details about my system and how to get a fully working mac os sierra.

**Comment by Healian** [comment]
You actually fucked up Creative CA0132 in the latest .18 release 👍  .17 works but no sound control i thought the issue is related to my PC bruh :D. can we at least get this working, AppleALC is very useful and i am willing to contribute as much as i can/know to make it better.

**Comment by vit9696** [comment]
Is this [change](https://github.com/vit9696/AppleALC/commit/f4e9d554b7e5d12047f911570319ddd8539f261f) the one that broke things for you?
CC @vandroiy2013

**Comment by Healian** [comment]
yea seems to be. the previous release pkg v1.0.17 works okay (regarding audio quality and outputs) even with sierra 10.12.2. after this change AppleALC no longer work on any version of sierra with me.

**Comment by vit9696** [comment]
Well. The situation with this codec is close to terrible.

We have 4 layouts submitted… and basically nobody maintains them. They somehow exist, somewhat work (either without volume controls, or with random noise @_@)… and we get kicked by people like you who claim that something randomly fails.

Please understand that none of us have that codec, and we are not really responsible for the bugs existing in its resources. I reverted the commit mentioned above [here](https://github.com/vit9696/AppleALC/commit/c196f31d1ae5f0029f568c6dd2d0653f5d394c61), so you could recompile AppleALC and it will work just like before, like 1.0.17.

However, if we get any more reports claiming that CA0132 does not work once again, the only action we could perform is to drop this codec support completely. It simply is unmaintained and nobody familiar to that hardware could come and say that this is wrong, this is right, and the following part needs to be rewritten in the other way. Thank you for understanding.
