### ISSUE TITLE
About UserPatches.plist,How to use it。

### ISSUE THREAD

**Issue by melxman** [vit9696/AppleALC#109]
I hope you can provide the contents of this document template, I am willing to test.

**Comment by vit9696** [comment]
Hi,
UserPatches.plist is not really for public usage but… it is just an array of patches applied unconditionally. One could find a template in Controllers.plist or in any codec Info.plist.

So you edit Kexts.plist with a kext you need to patch (its id and path). Then you insert an entry into UserPatches.plist in a usual way: Name, Count, Find, Replace, MinKernel, MaxKernel.
