### ISSUE TITLE
laptop msg ge62 6qf 2.1 audio subwoofer

### ISSUE THREAD

**Issue by florentino97425** [vit9696/AppleALC#111]
Hi,
I need help to patch my config data, platform and layout.
I follow this guide: http://osxarena.com/2015/03/best-all-in-one-patch-applehda-guide/
And I tried to get my internal speaker works but I see 3 speakers in my config data and I don't know how to config them.
Can I get some help, please.

[Archive.zip](https://github.com/vit9696/AppleALC/files/663733/Archive.zip)

**Comment by vit9696** [comment]
Hi,

We are not helping to build codec resources here. Please read the FAQs and create them. Once you are done you could submit them for later inclusion.

Thanks for understanding.
