### ISSUE TITLE
Intel HD 530 HDMI audio out

### ISSUE THREAD

**Issue by dodvip123** [vit9696/AppleALC#113]
Is it possible to add HDMI audio support for Skylake laptop HD530 (0x191b0000)?

**Comment by vandroiy2013** [comment]
Maybe in a few days.

**Comment by dodvip123** [comment]
Cool, thanks for the reply!

**Comment by vandroiy2013** [comment]
Added https://github.com/vit9696/AppleALC/commit/c70a8408fedd81d85fa8085a436690f23cf5b07c
Try it. Report.

**Comment by dodvip123** [comment]
how can I try it? I don't know how to build the kext myself

**Comment by vandroiy2013** [comment]
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/678425/AppleALC.kext.zip)

**Comment by dodvip123** [comment]
did not work, when connected with HDMI my system preferences only showed my internal speakers. Btw audio after sleep isn't working either for ALC256

**Comment by vit9696** [comment]
Well, submit the patch that works for you, and we might consider adding.
Regarding sleep issues — read CodecCommander manual, it needs to be set up.

**Comment by vandroiy2013** [comment]
@dodvip123, Obviously problems are on your side. hda-gfx->onboard 1 for IGPU and HDEF needed!!!
![2016-12-30 18 18 32](https://cloud.githubusercontent.com/assets/8144780/21568349/75374126-cebc-11e6-89f9-d9111f323207.png)
Tested on my desktop Skylake rig - works perfect.

**Comment by dodvip123** [comment]
![hda-gfx](https://cloud.githubusercontent.com/assets/15620248/21571307/4957eb3e-cece-11e6-8077-c47ddb576f0f.png)
![layout](https://cloud.githubusercontent.com/assets/15620248/21571308/4ba23bec-cece-11e6-946c-e28e8aa6999e.png)
Is there something obvious I'm missing?

**Comment by vandroiy2013** [comment]
Without IOreg i can't say anything... Screenshots are usefull

**Comment by dodvip123** [comment]
here is my IOreg, thanks for your help
[ALC256.zip](https://github.com/vit9696/AppleALC/files/679686/ALC256.zip)

**Comment by vandroiy2013** [comment]
You don't have HDMI codec device at all in IOreg. For comparison my IOreg and yours... Yours missing HDMI device that should be in HDEF section... Take a look... I don't know how to help you... Try to not use FakePCIID.kext and use only Clover injection. So the problems are not in AppleALC as i said before. Good luck and Happy New Year)))
![2016-12-31 17 59 37](https://cloud.githubusercontent.com/assets/8144780/21578313/05dd60b2-cf84-11e6-86ad-184d5635d214.png)

**Comment by dodvip123** [comment]
Thanks again for your help, I will look into it. Happy new year!

**Comment by dodvip123** [comment]
[ALC256.zip](https://github.com/vit9696/AppleALC/files/679720/ALC256.zip)
Could you take a quick look at HDEF now? I've a HDMI device but still not working

**Comment by vandroiy2013** [comment]
I told you try NOT to use FakePCIID.kext. I don't know how it affects HDMI sound... And it also could run HDMI sound. Maybe there is conflict between FakePCIID and AppleALC... You MUST always use one method instead of using two methods together.
