### ISSUE TITLE
CA0132 Issues with Gigabyte z170x Gaming 7

### ISSUE THREAD

**Issue by AppleMike** [vit9696/AppleALC#117]
Hi,

The last release of AppleALC have great improvements, now I got volumen control and HDMI output(HE530) but I do not have headphone output, it doesn't work.

Could you give any solution to solve this issue?

Thanks a lot for you job...!!!

**Comment by vit9696** [comment]
https://github.com/vit9696/AppleALC/issues/108#issuecomment-268016734
