### ISSUE TITLE
Add Support ALC282 For Dell Inspiron 3521

### ISSUE THREAD

**Issue by Generation88** [vit9696/AppleALC#118]
Hello bro,

please add support for alc282 layout28 for dell inspiron 3521

i have attached the layout28 & & platform files & also the verbs

[Resources.zip](https://github.com/vit9696/AppleALC/files/679606/Resources.zip)

**Comment by vandroiy2013** [comment]
Layout 28 is already in use. Test it with another free layout-id and give me updated resources. Thanks!

**Comment by Generation88** [comment]
[Resources.zip](https://github.com/vit9696/AppleALC/files/721865/Resources.zip)

Layout ID Is 29 Now....& also files are updated...now please add them to applealc as fast as possible & also rebuild & post the new kext

**Comment by vandroiy2013** [comment]
Added.

**Comment by Generation88** [comment]
please upload the new kext in releases

**Comment by vandroiy2013** [comment]
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/726701/AppleALC.kext.zip)

**Comment by Generation88** [comment]
[Archive.zip](https://github.com/vit9696/AppleALC/files/727024/Archive.zip)


sorry broda....i forgot to add layout id 29 in my layouts....can u update the attached layouts & post the new kext please

**Comment by vit9696** [comment]
@Generation88 sorry? Why do you ask for a compiled kext here? Clearly if you build your own resources you are supposed to test them. Use Xcode and make your own kext. We are not your build bot. As for layout-id 29, please create a new issue and explain why this layout is needed.

**Comment by vandroiy2013** [comment]
@Generation88 Those layout-id inside layout.xml.zlib doesn't matter...

**Comment by Generation88** [comment]
@vit9696 i am a new developer bro...soon will learn everything.....i understand your feeling...dont worry i will try to build my own next time

@vandroiy2013 okk brother thank you
