### ISSUE TITLE
Layout-ID 9 for Via VT2020/21

### ISSUE THREAD

**Issue by Fredde2209** [vit9696/AppleALC#119]
The Via VT2020/21 works best with a patched AppleHDA and a DSDT-Patch, that includes Layout-ID 9. But the AppleALC only knows the IDs 5 and 7, so Audio doesn't work that well as it does with 9 (knowledge based on reports by people at hackintosh-forum.de). Here is a Link to the AppleHDA and DSDT Patch: http://www.insanelymac.com/forum/files/file/622-via-vt20202021/%C2%A0
Thanks :)

**Comment by vandroiy2013** [comment]
Please provide resources, patches and pinconfig separately for this layout. Don't have time to compare patched AppleHDA with vanilla AppleHDA... Thanks

**Comment by Fredde2209** [comment]
I'd say the AppleHDA is patched via AppleHDA Patcher, but I don't know exactly... I will write the publisher and tell you

**Comment by vandroiy2013** [comment]
Existing resources in AppleALC was taken exactly from AppleHDA Patcher by @Mirone. Unpack zlib's and compare them....

**Comment by reyder** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LayoutID</key>
	<integer>9</integer>
	<key>PathMapRef</key>
	<array>
		<dict>
			<key>CodecID</key>
			<array>
				<integer>285606977</integer>
			</array>
			<key>Headphone</key>
			<dict/>
			<key>Inputs</key>
			<array>
				<string>Mic</string>
				<string>LineIn</string>
			</array>
			<key>IntSpeaker</key>
			<dict/>
			<key>LineIn</key>
			<dict/>
			<key>Mic</key>
			<dict/>
			<key>Outputs</key>
			<array>
				<string>Headphone</string>
				<string>IntSpeaker</string>
				<string>SPDIFOut</string>
			</array>
			<key>PathMapID</key>
			<integer>1</integer>
			<key>SPDIFOut</key>
			<dict/>
		</dict>
	</array>
</dict>
</plist>`

Here is platform
[http://pastebin.com/wJqcZZMR](url)

`Device (HDEF)
        {
            Name (_ADR, 0x001B0000)  // _ADR: Address
            OperationRegion (HDAR, PCI_Config, 0x4C, 0x10)
            Field (HDAR, WordAcc, NoLock, Preserve)
            {
                DCKA,   1, 
                Offset (0x01), 
                DCKM,   1, 
                    ,   6, 
                DCKS,   1, 
                Offset (0x08), 
                    ,   15, 
                PMES,   1
            }

            Method (_PRW, 0, NotSerialized)  // _PRW: Power Resources for Wake
            {
                Return (GPRW (0x0D, 0x04))
            }

            Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
            {
                Store (Package (0x10)
                    {
                        "AAPL,slot-name", 
                        "Built In", 
                        "name", 
                        "VIA VT2020/VT2021 Audio Controller", 
                        "model", 
                        Buffer (0x1C)
                        {
                            "VIA VT2021 Audio Controller"
                        }, 

                        "device_type", 
                        Buffer (0x11)
                        {
                            "Audio Controller"
                        }, 

                        "layout-id", 
                        Unicode ("\x0C"), 
                        "PinConfigurations", 
                        Buffer (0x30)
                        {
                            /* 0000 */  0x10, 0x40, 0x11, 0x01, 0xF0, 0x00, 0x00, 0x40,
                            /* 0008 */  0xF0, 0x00, 0x00, 0x40, 0xF0, 0x00, 0x00, 0x40,
                            /* 0010 */  0x20, 0x40, 0x21, 0x01, 0x60, 0x90, 0xa0, 0x90,
                            /* 0018 */  0x80, 0x30, 0x81, 0x01, 0xF0, 0x00, 0x00, 0x40,
                            /* 0020 */  0xF0, 0x00, 0x00, 0x40, 0x90, 0x61, 0x4b, 0x01,
                            /* 0028 */  0xF0, 0x00, 0x00, 0x40, 0xF0, 0x00, 0x00, 0x40 
                        }, 

                        "MaximumBootBeepVolume", 
                        Buffer (One)
                        {
                             0x40                                           
                        }, 

                        "hda-gfx", 
                        Buffer (0x0A)
                        {
                            "onboard-1"
                        }
                    }, Local0)
                DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                Return (Local0)
            }
        }
`

**Comment by vit9696** [comment]
Hello, what these resources are all about? Could you explain me what this layout 12 is for and whether we should include it?
