### ISSUE TITLE
Dell XPS 13 9343 (ALC288)

### ISSUE THREAD

**Issue by stealth658** [vit9696/AppleALC#121]
With AppleALC layout ID 3, I have working speakers/headphones (though jack-sensing takes a long time) and no microphone, and with CloverHDA on layout 13, I have working headphones with instant jack-sensing and internal microphone but no speaker Any chance you can help me figure out how to get everything working on AppleALC?

**Comment by vit9696** [comment]
Hello,
I am afraid not. Nobody here has enough time to dig into the resources unfortunately. We will merge the working ones if you make them, however.
Thanks for understanding.
