### ISSUE TITLE
Request patch for Asus V451LN and Asus N550

### ISSUE THREAD

**Issue by Ken-W-P-Huang** [vit9696/AppleALC#122]
Hi ,
Firstly thank you for your hard work to make patching AppleHDA so simply.
I have tried to use AppleALC to patch AppleHDA for Asus V451LN and Asus N550.
the internal speaker is working fine but there is noise when the laptop is injected with headset.
the sound card for  Asus V451LN is ALC 233 while  for Asus N550 is ALC668.
I have tried all the layout ids defined in AppleALC but get no luck.
Previously, I was using the patches credited to vusun123 and internal speaker, headset and microphone  are working perfectly .
Is it possible to  get these patches since he is one of the contributors?

**Comment by vit9696** [comment]
Hello, please post the patches you need here, and we will consider adding them. Thank you!
