### ISSUE TITLE
10.12.4 beta support?

### ISSUE THREAD

**Issue by anayw2001** [vit9696/AppleALC#123]
AppleALC is not being injected by Clover no matter what I set for Inject Kexts/Layout ID.

**Comment by vandroiy2013** [comment]
It's not the problem with AppleALC. This is clover problem. In 10.12.4 old kext injection didn't work. Update clover to 3985 or higher. https://sourceforge.net/p/cloverefiboot/code/3985/
[Clover_v2.3k_r3985.pkg.zip](https://github.com/vit9696/AppleALC/files/733983/Clover_v2.3k_r3985.pkg.zip)
