### ISSUE TITLE
ALC898  Codec

### ISSUE THREAD

**Issue by rkatuku** [vit9696/AppleALC#125]
Hi,

Thank you for providing this patch.  My Audio is detected in SR 10.12.2. But there is no sound from internal speakers, although microphone & headphones are working on Digital out with layout id 13. I have tried with all layout id's listed. And also sound from headphones is distorting a lot. Is there anything you could suggest is much appreciated.

I have MSI GS40 laptop, with Realtek ALC898 audio

Thanks You

**Comment by vandroiy2013** [comment]
Ask @insanelydeepak about this codec. Layout-id 13 was made by him exactly for this laptop.

**Comment by insanelydeepak** [comment]
its require to use Codec_commander with ALC898 laptops edition , if still don't work then need to rework on it .
