### ISSUE TITLE
Apple ALC256 No Sound

### ISSUE THREAD

**Issue by z04n** [vit9696/AppleALC#126]
Hello,

I have an Apple Inspiron 5000 5567 that is a Kaby Lake leveraging faked SkyLake hardware.  Realtek 3246/ALC256 is the installed audio, which works on a Windows 10 installation .

Using the AppleALC method via Clover/Kext/Other and injecting audio ID 13, devices and Intel High Definition Audio are listed, as well as the the audio icon showing that the audio should be working.  However, no audio can be heard.  I have also tried Deepak's CloverHDA and additional plist patches, but same result.

Thanks

**Comment by vit9696** [comment]
Hi,

If nothing helps you, you likely need custom resources created particularly for your system. Check the guides and make them (or ask somebody else to make them). Once they are ready and work for you, please create a new issue here and we will add them!

Thank you
