### ISSUE TITLE
IDT 92HD87B1/3 can you fix my sound card? I use applealc ,but "int mic" doesn't work

### ISSUE THREAD

**Issue by 2014macml** [vit9696/AppleALC#127]
here is codec.
[codec.TXT](https://github.com/vit9696/AppleALC/files/752829/codec.TXT)

Codec: IDT 92HD87B1/3
Address: 0
AFG Function Id: 0x1 (unsol 1) 
Vendor Id: 0x111d76d1
Can you fix it? My sound card "int mic",doesn't work
I use layout id 12

**Comment by vit9696** [comment]
Hi,

These resources were given to us by [Moore](https://applelife.ru/members/moorre.43841/), and I think they are not meant to work with exactly your hardware. Perhaps the mic node sequence is wrong. Check it out, and submit us a patch you get it work. You also might want to ask Moore himself whether mic works for him.

Vit

**Comment by 2014macml** [comment]
Sorry,I can't find and ask him,I don't know Russia,can you help?I have given the codec

**Comment by vit9696** [comment]
We are not really offering the codec support here.
I asked Moore myself, and he says that the resources are a direct copy of Mirone's resources altered by RehabMan. So you if you need any insight on your issue, you should ask them. 
He also mentioned that the microphone did work but in a rather weird manner: it would sometimes start overmodulating the incoming signal.

**Comment by 2014macml** [comment]
Could you build a program or project  that can build applealc with codec，I think it's great!

Or someone give codec,others build applealc.not everyone can build it .
Like me
My English is poor ，either.

**Comment by vit9696** [comment]
I am afraid Google is your friend here. The basic details on how to build AppleALC are detailed on the wiki.
