### ISSUE TITLE
ALC256 No Sound Updated w/ Info 

### ISSUE THREAD

**Issue by z04n** [vit9696/AppleALC#128]
Thanks, Vit!  I am beyond thankful for the guidance and support that you and the other developers provide.  In light of that, I will be putting together a guide as more folks will be purchasing Kaby Lake laptops and until Apple starts building with them, it'll require tweaking.  

-Dell Inspiron 5000 5567 15.6 1080/60 Touch Screen
-Intel i5 7200u
-8 GB 2400 MHz DDR4
-Intel HD620
-Realtek RTL8106E
-Intel Wireless-AC 3165 Model: 3165NGW (not supported and will replace)
-Realtek ALC3246

Issue:  Sound will not play through speakers or headphones.  Internal Speakers or Headphones (if plugged in) appear in SysPref/Sound/Output as devices and in Sound Effects, play sound effects through is Internal Speakers or Headphones.  Within Input, I can see Input Level meter working, but cannot validate as I have no sound. 

1. Followed steps listed in RehabMan's UEFI El Capitan install
-Used the plist HD620 plist listed in RehabMan's Laptop Config
-Added the following kexts to /EFI/Clover/kexts/Other:
-FakePCIID_Intel_HD_Graphics
-FakePCIID
-FakeSMC
-GenericUSBXHCI
-RealtekRTL8100
-SATA-100-series-unsupported
-VoodooPS2controller
-Applied Sherlock's Glitch Fix v3 to config.plist and updated devices  

2. Audio troubleshooting w/ native AppleHDA (each method attempted using a fresh install w/ step 1 above)
-Native Audio w/Clover and AppleALC 
--Validated that the HD620 plist includes “change HDAS to HDEF” and that it is enabled
--Config.plist/Devices/Audio is Injecting 13, per AppleALC wiki for ALC256 (3246)
--Downloaded AppleALC v1.0.18 and placed in /EFI/Clover/kexts/Other
--Reboot and no sound, exhibiting issues listed in the bolded issue above
-Insanely Deepak cloverHDA
--Per README: Layout ID 13 and DSDT patch HDEF (completed via Clover/ACPI patch)
--Updated config.plist/KernelAndKextPatches (plistedit pro) with the five listed in the config-CloverHDA.plist 
--Installed cloverHDA via Kext Wizard into /S/L/E

Attached files reflect the first troubleshooting scenario (AppleALC).  I did notice that there are three files at ALC256 (3246), which provide an info.plist and two zlibs.  The  guides do not reference updating these, but have found legacy instructions on how to update info.plist and zlibs on the native AppleHDA, so not sure if I'm missing a step?  That the assumption is that I've modded AppleHDA and these fixes address SIP?

I apologize if I've missed something, but will develop a guide and overview for this laptop that goes a little beyond.  I see hackintosh users as: L1 (Vit, Deepak, etc.), L2 (non-developers, but technical), and L3 (relies 100% on guides and unable to troubleshoot solo).  I want to aim this guide at the L3.

Thanks again!

[DSPCI.zip](https://github.com/vit9696/AppleALC/files/753302/DSPCI.zip)
[EFI.zip](https://github.com/vit9696/AppleALC/files/753303/EFI.zip)
[IOReg.zip](https://github.com/vit9696/AppleALC/files/753306/IOReg.zip)
[ScreenShots.zip](https://github.com/vit9696/AppleALC/files/753305/ScreenShots.zip)
[Troubleshooting.zip](https://github.com/vit9696/AppleALC/files/753304/Troubleshooting.zip)

**Comment by vit9696** [comment]
Thank you for your warm words. But should not this be put to the wiki or to some separate project? After all it is not directly an issue but an instruction unless I missed the point.

**Comment by z04n** [comment]
It's an issue as I can't get sound to play through the speakers. I provided the background in case there was a step I missed. 

Hoping you can help me to get sound playing through speakers and headphones?

**Comment by vit9696** [comment]
Understood. Unfortunately this is a problem with the resources we have in AppleALC, and not in AppleALC itself. Since the resources are submitted by various other people we do not offer any support for them. Thank you.

**Comment by z04n** [comment]
That makes sense, sorry for creating another issue. Do you recommend I place this in a troubleshooting forum, such as InsanelyMac?

Thanks again!

**Comment by vit9696** [comment]
Might be a good idea actually. But I think this needs someone with resource creation skills.
