### ISSUE TITLE
cx 20753 ext/internal mic not working

### ISSUE THREAD

**Issue by xinyuwufei** [vit9696/AppleALC#129]
ext mic does not work as expected since the issue exists a long time (already asked Mirone before, refer to [applehda patch problem for Conexant CX20753/4 (14f1:5111)](https://www.tonymacx86.com/threads/applehda-patch-problem-for-conexant-cx20753-4-14f1-5111.191289/))

internal mic works out of box on aDummyHDA.kext(using appleHDA Patcher1.7).
so that I think the issue is related to layout file(probably not the latest one)

**Comment by vandroiy2013** [comment]
The files are identical. CX20753/4 was added a few hours after AppleHDAPatcher 1.7 released. https://github.com/vit9696/AppleALC/commit/e91b5820521b50fdd85f4a83b49c486ae84fa1fb. Files are exactly latest... Before using AppleALC.kext check your config.plist. Delete ALL audio patches from KextToPatch. Also check your AppleHDA.kext is clean (vanilla). Use this command in terminal `codesign --verify --no-strict /System/Library/Extensions/AppleHDA.kext/`.

**Comment by xinyuwufei** [comment]
I downloaded the latest released file, issue is gone😆
 probably I did or compiled sth wrong before.
thanks for your help! 😆

**Comment by hellohasbi** [comment]
Hello, I've successfully for build AppleALC with Lilu, but my mic cause restart my hackintosh.
Problem:
When I pluged headphone jack, and then go to SysPref>Sound>Input my hackintosh got reboot. How to fix it?
