### ISSUE TITLE
how to add support for my laptop

### ISSUE THREAD

**Issue by Art-Chen** [vit9696/AppleALC#130]
I have a x401a laptop use alc270,and it can work best by patch applehda,using Hackintosh Vietnam Tool,alc270 for x401a,so can you add resources for my laptop?if you can't, tell me how to do it please.thanks!

**Comment by Art-Chen** [comment]
now i'm using layout 28,my headphone auto switch can't work and i can only use speaker

**Comment by vandroiy2013** [comment]
https://github.com/vit9696/AppleALC/wiki/Adding-codec-support
