### ISSUE TITLE
new applealc (1.0.19) not working, but 1.0.10 works...

### ISSUE THREAD

**Issue by hectorox** [vit9696/AppleALC#135]
hello,
I am on El Capitan 10.11.5.
Actually I was using applealc 1.0.10 (with custom pinconfiguration, Mirone - IDT 92HD91BXX, Codec-ID: 287143648, Layout-ID: 0) and this is working fine. Now I wanted to update applealc to 1.0.19, I have changed the item 182 to my needed configuration. After installing the kext there is no sound anymore. Have tried everything, but still no sound. When I install my old applealc 1.0.10 again sound is working fine. Any suggestions?

**Comment by vit9696** [comment]
Hello,
I do not have a crystal ball to help you, yet we added a revision-id in 1.0.15.
`Added revision-id in IDT 92HD91BXX info.plist`
It might be that your codec revision differs from 0x100102.
Consider submitting your resources.

**Comment by hectorox** [comment]
If you want I can send you my resources (I have created them by myself for an EliteBook 820 G1).
I have:
- layout0.xml.zlib (custom created)
- platforms.xml.zlib (edited for right pathmap)
- codec id: 287143648
- pinconfiguration (custom created)

Do you need something else?

I do not mind, if you would add this specific codec configuration for an EliteBook 820 G1 into your AppleALC build

**Comment by vit9696** [comment]
Certainly not until you get your stuff fixed. Also change your layout-id to something after 12.

**Comment by vit9696** [comment]
Well, the same way you got your codec id. Via ioreg.

**Comment by hectorox** [comment]
Ah thank you! Yes, I found it in my documents. The revision-id for my codec is:

0x100303

**Comment by vit9696** [comment]
Well, add it and check if it works. If it does, submit the resources here (with some other layout-id, from 11 to 99, avoiding already used ones) via a pull request or as an archive.  
Then wait until @vandroiy2013 finds some time to verify the materials and adds them to AppleALC codec database.

**Comment by hectorox** [comment]
you mean by changing it to: 0x100102 or to my original one: 0x100303?

(Also, I need to check how to add a custom revision-id to my dsdt...)

**Comment by vandroiy2013** [comment]
Just add one more line with your revision-id in Revision section in info.plist

![2017-02-17 22 22 43](https://cloud.githubusercontent.com/assets/8144780/23081943/d143bf66-f55f-11e6-9f2c-dabd79fbb337.png)

**Comment by hectorox** [comment]
It is working again, thank you :)

**Comment by vandroiy2013** [comment]
Now provide your resources, updated info.plist and pinconfig info.plist so we can add them for everybody.
