### ISSUE TITLE
Just Line Out works on ALC1220?

### ISSUE THREAD

**Issue by fundon** [vit9696/AppleALC#136]
I installed the latest source https://github.com/vit9696/AppleALC/commit/1571d14cf6479cdea44e3283f960b842a312d09f and it works.

But only the `Line Out` 2 is available and `Headphones` does not work. Is it right?

**Comment by vandroiy2013** [comment]
You should ask author of this resources
http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/?p=2369930
