### ISSUE TITLE
ALC1150 unstable audo level

### ISSUE THREAD

**Issue by TheCuriousHacker** [vit9696/AppleALC#137]
I'm not sure that it's ALC1150 related issue, it ight be related something else, but I ahve unstable audio output level. Volulme level changes by itself up and down.

Devices:

Built-in Microphone:

  Default Input Device:	Yes
  Input Channels:	2
  Manufacturer:	Apple Inc.
  Current SampleRate:	48000
  Transport:	Built-in

Built-in Output:

  Default Output Device:	Yes
  Default System Output Device:	Yes
  Manufacturer:	Apple Inc.
  Output Channels:	2
  Current SampleRate:	44100
  Transport:	Built-in

Built-in Line Output:

  Manufacturer:	Apple Inc.
  Output Channels:	2
  Current SampleRate:	44100
  Transport:	Built-in

Built-in Line Output:

  Manufacturer:	Apple Inc.
  Output Channels:	2
  Current SampleRate:	44100
  Transport:	Built-in

Built-in Digital Output:

  Manufacturer:	Apple Inc.
  Output Channels:	2
  Current SampleRate:	44100
  Transport:	Built-in

**Comment by vandroiy2013** [comment]
It is definitely not AppleALC problem. Check if you use any audio enhancers like boom2 or something else.

**Comment by ctf0** [comment]
am having a similar issue aswell ,but this time the audio suddenly starts to delay the output.

- i was using boom2 so i removed but still nothing changed
- i tried different ids under clover but again all the same

the only solution is to stop whatever is playing `online video/audio, itunes, vlc, etc...` open the `Sound` pref pans and switch between the alert sounds until the delay is gone.

not sure what exactly is the issue or how to debug it.

**Comment by TheCuriousHacker** [comment]
> It is definitely not AppleALC problem. Check if you use any audio enhancers like boom2 or something else.

I'm not using any  audio enhancers!
