### ISSUE TITLE
Not work after installing HDMI clover

### ISSUE THREAD

**Issue by diepnt90** [vit9696/AppleALC#139]
Dear ,

Im using applealc well. today i installed HDMI clover for using HDMI audio also.

HDMI work well but Applealc become to not work.

could you help me how to fix?

i'd like to use both of them. HDMI audio and audio jack output for better speaker sometimes.

**Comment by vandroiy2013** [comment]
I don't know what it is "HDMI clover"...

**Comment by diepnt90** [comment]
it is here:

https://github.com/toleda/audio_CloverHDMI

enable sound output for HDMI.

**Comment by vandroiy2013** [comment]
So what? What HDMI? What video card? Need details. Or you think i'm psychic? Why should i drain information from you?

**Comment by vit9696** [comment]
@vandroiy2013 people think we have a large collection of vintage crystal balls to look into.
Closing until proper information is given.
