### ISSUE TITLE
ALC255 CAUSE ABRUPT CPU AND MEMORY USES,combo jack not working

### ISSUE THREAD

**Issue by Genxster1998** [vit9696/AppleALC#144]
Device:-Dell Vostro 3546(haswell) Realtek audio alc3223 aka alc255
issue:-
i have installed applealc with layout id 3 .also used applehda patcher app ,both cause extensive cpu and memory use by kernel_task process.
reference:-
https://www.tonymacx86.com/threads/solved-patched-applehda-maxing-out-cpu-utilization.211829/

**Comment by vandroiy2013** [comment]
We know about that. @Mirone will fix this issue as soon as possible. Use layout-id 13 by @insanelydeepak. It works pretty fine.

**Comment by Genxster1998** [comment]
yeah,just figured out used layout 17 ,its superb

**Comment by vandroiy2013** [comment]
Just added updated resources by @Mirone. Try it if you have time and report back. Thanks...

**Comment by vandroiy2013** [comment]
Here is updated AppleALC with new resources. Use layout-id 3. Report about kernel_task usage.
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/842021/AppleALC.kext.zip)
