### ISSUE TITLE
Conexant CX20756: Wrong codec files

### ISSUE THREAD

**Issue by STiXzoOR** [vit9696/AppleALC#145]
Hi, thanks for this awesome kext but i think the files for Conexant CX20756 are the wrong ones because it doesn't work on my laptop. The audio is greyed out and no inputs/output are available. I'm using a vanilla AppleHDA and i checked if the AppleALC loads first and it does. If you can find what's wrong you will be my saviour. Thanks.

**Comment by vandroiy2013** [comment]
Hm... You right... I'll contact @Mirone about this codec...

**Comment by vandroiy2013** [comment]
Well @Mirone will update resources as soon as he can. I'll post here after update.

**Comment by Mirone** [comment]
@vandroiy2013 ,
I find this files from Old AppleHDA Patcher
Are correct. [CX20756](https://github.com/Mirone/AppleHDAPatcher/tree/master/Patches/Laptop/CX20756)

**Comment by vandroiy2013** [comment]
@Mirone , Thanks. i will update them as soon as possible!

**Comment by vandroiy2013** [comment]
@Mirone , Sorry but a unpack layout3.xml.zlib from your link and see Codec-id from CX20751
![2017-03-20 18 19 51](https://cloud.githubusercontent.com/assets/8144780/24109673/0ffb1900-0d9a-11e7-94b8-26ab383f26ef.png)

**Comment by Mirone** [comment]
@vandroiy2013 ,
ok, it's very easy fixed, you make me a favor?
you can fix typo for me?
351359252 = 0x14F15114,
other files is correct.

**Comment by vandroiy2013** [comment]
OK. Changed! 
@STiXzoOR , Test it please and report back. Here is updated prebuild AppleALC.kext
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/855736/AppleALC.kext.zip)

**Comment by STiXzoOR** [comment]
Thanks @Mirone and @vandroiy2013 for the support. I'm gonna try it as soon as i can and report back.

**Comment by STiXzoOR** [comment]
So the sound now works(both speakers and headset) but the external mic doesn't. It doesn't even show up in inputs. When connecting my headset the input stays the same(internal mic).

**Comment by vandroiy2013** [comment]
Ask @Mirone to help you with this issue...

**Comment by Mirone** [comment]
@STiXzoOR ,
send me your codec_dump.

**Comment by STiXzoOR** [comment]
Here, straight from linux: [card1-codec#0.txt](https://github.com/vit9696/AppleALC/files/858163/card1-codec.0.txt)

**Comment by STiXzoOR** [comment]
@Mirone also i'm sending you the Pathmaps that i played with the other day, which seems they kinda work. Actually here is the report:

Speakers: Yes
Headphone: Yes
Internal Mic: Yes
External Mic: No (but shows up in the inputs)

[Platforms.xml.zip](https://github.com/vit9696/AppleALC/files/858196/Platforms.xml.zip)

**Comment by Mirone** [comment]
Please try this: http://www.insanelymac.com/forum/topic/293863-applehda-patch-requests/page-42?p=2383785#entry2383785

**Comment by STiXzoOR** [comment]
I barely understand what he is saying and i can't download the SSDT for some reason :-/ :-/

**Comment by Mirone** [comment]
Yes, but some issues are needed,
I can do this for you, but only at night (Brazil time).

**Comment by STiXzoOR** [comment]
Yeah sure no problem i can wait. thanks man

**Comment by Mirone** [comment]
@STiXzoOR,
try this files, delete AppleALC, install AppleHDA+CodecCommander in: System/Library/Extensions.
put SSDT-1 in: EFI/Clover/ACPI/Patched.
try both versions of AppleHDA in the Attached files.
[AppleHDA-278.56-CX20756_v2.zip](https://github.com/vit9696/AppleALC/files/860117/AppleHDA-278.56-CX20756_v2.zip)

**Comment by STiXzoOR** [comment]
@Mirone, i tested both versions and non of them was working. No audio at all.

**Comment by Mirone** [comment]
@STiXzoOR,
try AppleALC+DSDT+CodecCommander.

**Comment by STiXzoOR** [comment]
@Mirone emm ok for some reason the audio is not greyed out but no sound is coming out of the speakers and headphones. In fact it doesn't switch to headphone output when i plug in the headset.

Also @vandroiy2013 can you please compile me the AppleALC with node 19 instead of 18 for the external mic since i think it's the problem for not showing external min in inputs when i have the headset plugged in? Thanks.

**Comment by vandroiy2013** [comment]
@STiXzoOR, Try to compile it yourself))) Xcode is free of charge in App Store and AppleALC source code is open and ready for download. In Tools folder you'll find scripts for unpacking/packing zlib's. Don't forget to put in AppleALC folder debug version of Lilu.kext.  Sorry, but i'm not a compile bot:).
