### ISSUE TITLE
HD530 HDMI not working ...

### ISSUE THREAD

**Issue by Flowwwww** [vit9696/AppleALC#147]
Hello, 
I don't manage to get sound through HDMI. I have AppleALC 1.0.19.kext and Lilu.kext installed on my clover. Sound through AUX output is working great (ALC1150 Realtek driver).

I don't understand why it doesn't work. 
Pref pane is showing 4 outputs but none is working through HDMI 

![parametres son](https://cloud.githubusercontent.com/assets/17790045/24264200/ef5c4260-0fff-11e7-8f36-0df08518e1b3.png)

IOReg recognized well both drivers
![ioreg sound](https://cloud.githubusercontent.com/assets/17790045/24264229/0edfe6e6-1000-11e7-8557-a9bcaf36c19f.png)

I must miss something but I don't know what ...

**Comment by vandroiy2013** [comment]
> I must miss something but I don't know what ...

How can i help you without reports? IOReg & DarwinDumper needed...

**Comment by Flowwwww** [comment]
Sorry ... here it is

[DarwinDumper_3.0.3_23.03_20.04.08_iMac17,1_AMI_X64_3763_Sierra_16D32_florent_olivro.zip](https://github.com/vit9696/AppleALC/files/865874/DarwinDumper_3.0.3_23.03_20.04.08_iMac17.1_AMI_X64_3763_Sierra_16D32_florent_olivro.zip)
[iMac de Florent.ioreg.zip](https://github.com/vit9696/AppleALC/files/865877/iMac.de.Florent.ioreg.zip)

**Comment by vandroiy2013** [comment]
Here you go. Replace with this config. Reboot. Provide IOReg. 
[config.plist.zip](https://github.com/vit9696/AppleALC/files/865942/config.plist.zip)

**Comment by vandroiy2013** [comment]
Also UPDATE your AppleALC.kext. You use 1.0.19. It Works WITHOUT Lilu.kext. Install AppleALC 1.1.0 from here https://github.com/vit9696/AppleALC/releases/tag/1.1.0

**Comment by Flowwwww** [comment]
Updated to 1.1.0.
your config.plist make macOS crashes at apple logo boot ... Here is my original config.plist.
[config.plist.zip](https://github.com/vit9696/AppleALC/files/866174/config.plist.zip)
What do i have to add?

**Comment by Flowwwww** [comment]
AppleALC 1.1.0 make Finder crashes several times before we can use it 
![finder crash](https://cloud.githubusercontent.com/assets/17790045/24270113/18f6e148-1014-11e7-8532-74755cfbccb4.png)

**Comment by vandroiy2013** [comment]
FIRST OF ALL UPDATE Clover to latest version!!! https://sourceforge.net/projects/cloverefiboot/ and then replace your config with mine.

> your config.plist make macOS crashes at apple logo boot ...

It shouldn't crash system... Don't touch anything in it. And DON'T open it in CloverConfigurator! Just replace it and boot in Verbose mode and with debug=0x100 in bootargs. If panic take a picture of it and attach it here...

**Comment by vandroiy2013** [comment]
AND DELETE HDAEnabler.kext! You don't need it at all

**Comment by Flowwwww** [comment]
> AND DELETE HDAEnabler.kext! You don't need it at all
Where is it? Can't find it in CLOVER folder ...

**Comment by Flowwwww** [comment]
Panic 
![vlcsnap-2017-03-23-23h06m07s380](https://cloud.githubusercontent.com/assets/17790045/24272382/5e7a1042-101d-11e7-8008-7905aa3c2edf.png)

**Comment by Flowwwww** [comment]
Better screenshot !
![20170326_163401](https://cloud.githubusercontent.com/assets/17790045/24332377/b52a3ce4-1245-11e7-9d5d-c807bb5153fe.jpg)

**Comment by vandroiy2013** [comment]
[config.plist.zip](https://github.com/vit9696/AppleALC/files/870833/config.plist.zip)

**Comment by vandroiy2013** [comment]
Update Clover to r4035!!!!

**Comment by Flowwwww** [comment]
CLOVER UPDATED NOW (I made a mistake when first updating ... My bad)

Screen shot with new config.plist :
![20170326_173037](https://cloud.githubusercontent.com/assets/17790045/24332605/e778bb7c-1249-11e7-95b2-8b3878da6757.jpg)

**Comment by vandroiy2013** [comment]
Try this 
[config.plist.zip](https://github.com/vit9696/AppleALC/files/870861/config.plist.zip)

**Comment by Flowwwww** [comment]
Looks like it's the same ...
![20170326_175914](https://cloud.githubusercontent.com/assets/17790045/24332845/ee3d9cbc-124d-11e7-99aa-d37bd018f4e9.jpg)

After it's crashing like this
![20170326_175915](https://cloud.githubusercontent.com/assets/17790045/24332852/02c5125a-124e-11e7-8dfa-d2afff500387.jpg)

**Comment by vandroiy2013** [comment]
What connection you use? HDMI-HDMI or adapters? Does your display have speakers? Does they work with Intel HDMI in Windows? What version of BIOS do you have now? What settings in BIOS now? Does HDMI Audio turned on in BIOS? Reset it to Defaults. Then tune it like this

Primary Display [CPU Graphics]
iGPU Multi-Monitor [Disabled]
RC6(Render Standby) [Disabled]
DVMT Pre-Allocated [256M]
HD Audio Controller [Enabled]
Front Panel Type [HD Audio]
SPDIF Out Type [SPDIF]
DVI Port Audio [Enabled]

Then try to boot with this config...
[config.plist.zip](https://github.com/vit9696/AppleALC/files/870880/config.plist.zip)

**Comment by Flowwwww** [comment]
What connection you use? HDMI-HDMI 
Does your display have speakers? Of course yes !!!
Does they work with Intel HDMI in Windows? Yes
What version of BIOS do you have now? I don't know that ...

RESETED BIOS and turned options like you said. WITH secure boot to Other OS and Serial POrt disable

Kernel Panic :

![20170326_211546](https://cloud.githubusercontent.com/assets/17790045/24334401/c4465ae0-1269-11e7-9d77-9fa723282733.jpg)

**Comment by Flowwwww** [comment]
Oh wait ... 
Forgot to put XHCI Hand-off to Enabled and legacy usb support to enabled.
Now i have this 
![20170326_214022](https://cloud.githubusercontent.com/assets/17790045/24334593/11a6b688-126d-11e7-8520-a5e29db2d00c.jpg)

**Comment by Flowwwww** [comment]
AppleHDA.kext restored with the original from Installer but same problem ...

**Comment by Flowwwww** [comment]
problem fixed with macOS 10.12.4. Thanks for help !

**Comment by vandroiy2013** [comment]
With my config.plist?

**Comment by Flowwwww** [comment]
Quite the same. Injection had to be done via Arbitrary section.
10.12.4 include a better support for HD530 iGPU, no need to inject Intel anymore and no need to injet id-platform.


Here is the config.plist that worked :
[config.zip](https://github.com/vit9696/AppleALC/files/881471/config.zip)

**Comment by Flowwwww** [comment]
10.12.4 fixed the problem of loading graphic firmware at boot time i guess

**Comment by vandroiy2013** [comment]
OK.

**Comment by Flowwwww** [comment]
Thanks for help ;)

**Comment by vandroiy2013** [comment]
You are welcome)))
