### ISSUE TITLE
Not working on MacOS 10.12.4

### ISSUE THREAD

**Issue by utegental** [vit9696/AppleALC#148]
Was working on 10.12.3, but not working on 10.12.4. Tried to use different layers. Tried to update to latest version. Even downloaded latests sources and tried to use kext compiled from them.
Is there any solution?

**Comment by vandroiy2013** [comment]
Nothing changed in 10.12.4 should work as in 10.12.3. My ALC887 and Intel HDMI works well...

**Comment by utegental** [comment]
My ALC1150 doesn't. Motherboard MSI LGA1150 Z97A GAMING 7.
I see device in System report:
![screenshot at mar 28 22-25-06](https://cloud.githubusercontent.com/assets/431860/24416111/7a42663a-1405-11e7-9a50-102700ff8111.png)

But I don't see anything in audio devices:
![screenshot at mar 28 22-25-31](https://cloud.githubusercontent.com/assets/431860/24416165/b2669982-1405-11e7-8060-5aa6e162c46f.png)

**Comment by utegental** [comment]
Found solution. Was needed to upgrade clover to latest version - 4035.
