### ISSUE TITLE
ALC1150 audio works fine on case's 3.5mm jack, very quiet and crippled/distorted when plugged in to the MOBO's 3.5mm jack.

### ISSUE THREAD

**Issue by XWhatevs** [vit9696/AppleALC#149]
NOTE: Testing this with headphones which are 100% working (tested them in Windows and on other devices). 

I'm on Sierra (10.12.4), ALC1150, latest version of Clover, and latest versions of AppleALC.kext and Lilu.kext. 

So, the headphones produce perfect audio when they're plugged into the 3.5mm jack that's located on my CASE (in Sys Pref's they recognized as "Headphones"), but if they're plugged into the 3.5mm jack located directly on my motherboard (in Sys Prefs recognized as "Internal Speakers"), they produce pretty quiet and distorted/crippled audio (in other works, totally unusable audio).

I also tested this with my speakers (also 3.5mm). 

A guy posted the same issue as mine on toleda's CloverALC repo 3 days ago: 

https://github.com/toleda/audio_CloverALC/issues/100

Same codec, exactly same issue as mine, just that's he's using toleda's CloverALC.

**Comment by vandroiy2013** [comment]
Hi. You should wait when Toleda fix this issue. We use his resources in AppleALC. Please post here link to updated resources or workaround when its ready and i'll update kext! This issue will be open for some time. Thanks.

**Comment by XWhatevs** [comment]
@vandroiy2013 Alright, I've submitted an issue to the repo of toleda's CloverALC.
