### ISSUE TITLE
Not working on Gigabyte GA-Z170N-WiFi (ALC1150)

### ISSUE THREAD

**Issue by utegental** [vit9696/AppleALC#154]
It's not working on Gigabyte GA-Z170N-WiFi. This motherboard has ALC1150 audio and I see library is loaded without any problems, but I see nothing in audio devices.
I have another build with MSI Z97A Gaming 7, which also has ALC1150 and there all is okay.
May be I can provide some additional info? Logs, dumps etc.

**Comment by vandroiy2013** [comment]
Definitely the problem is on your side. AppleALC works pretty well with this board... Provide full  DarwinDumper report, IORegistry report and your EFI folder...

**Comment by vandroiy2013** [comment]
Also show me output of this command
codesign --verify --no-strict /System/Library/Extensions/*.kext/

**Comment by vandroiy2013** [comment]
And 
codesign --verify --no-strict /Library/Extensions/*.kext/

**Comment by utegental** [comment]
[EFI.zip](https://github.com/vit9696/AppleALC/files/917374/EFI.zip)
[DarwinDumper_3.0.3_12.04_23.22.50_iMac17,1_AMI_X64_4049_Sierra_16E195_zinp.zip](https://github.com/vit9696/AppleALC/files/917372/DarwinDumper_3.0.3_12.04_23.22.50_iMac17.1_AMI_X64_4049_Sierra_16E195_zinp.zip)
[IORegistryReport.zip](https://github.com/vit9696/AppleALC/files/917373/IORegistryReport.zip)
[codesign.zip](https://github.com/vit9696/AppleALC/files/917371/codesign.zip)

**Comment by vandroiy2013** [comment]
OK. Delete your EFI folder and replace it with this EFI. Don't change anything in it. After login provide IOReg
[EFI.zip](https://github.com/vit9696/AppleALC/files/917422/EFI.zip)

**Comment by utegental** [comment]
It didn't loaded. It breaking on step of Intel HD 530 initialisation. But with one difference. Usually on this step I see Mac logo teared to parts horizontally. Here is happening the same but colours was changed to purple

**Comment by utegental** [comment]
So, You suppose that the problem in graphics card?

**Comment by vandroiy2013** [comment]
Replace config.plist and try again. Only config.plist in my EFI folder!!!
[config.plist.zip](https://github.com/vit9696/AppleALC/files/918475/config.plist.zip)

**Comment by utegental** [comment]
The same result

**Comment by utegental** [comment]
What next we can do?

**Comment by utegental** [comment]
May be the problem is caused not only by intel graphics and by something else? I tried to put MSI GTX960 4GB and install web drivers. Of course Intel HD 530 I disabled in bios. And sound devices didn't appeared. I tried just half of possible layers, but I guess that will not solve my problem.

**Comment by utegental** [comment]
And as I see in 'sudo kextstat' AppleAlc didn't loaded...

**Comment by vandroiy2013** [comment]
Try this config
[config.plist.zip](https://github.com/vit9696/AppleALC/files/919217/config.plist.zip)

**Comment by utegental** [comment]
And that one is working :-)
What You changed?

**Comment by vandroiy2013** [comment]
Compare your previous config.plist with mine... Audio works? I can close issue?

**Comment by utegental** [comment]
Yeah, sure. Thanks!

**Comment by vandroiy2013** [comment]
You are welcome
