### ISSUE TITLE
Need help with Clevo P750-DM (Eurocom Sky X4)

### ISSUE THREAD

**Issue by telicha** [vit9696/AppleALC#155]
Thanks for AppleALC! It is the best patching for sound out there!  I almost got it working on my P750-DM laptop after a few iterations. I like that I can put it in the EFI and as long as AppleHDA.kext does not change too much, I will not have problems with updates or even a re-install. The laptop has a Realtek ALC 892 codec. It has speakers thru a SoundBlaster X-Fi MB5, a built-in microphone, and 4 jacks - SPDIF/out, Headphone, Microphone, Line-in. AppleALC works **almost** perfect with layout 1 - except for the fact that the internal microphone and the microphone jacks are switched. When I select the internal microphone, it does not register any sound at all, but if I plug an external microphone, it works. There is no other sound input I can select, in the settings, so I can't use the microphone. Output sounds seems to be fine - except that I did not bother to test the SPDIF jack ... I tried all the other layouts - none of them work right, except that layout 4 the microphone works fine, but then there is no sound output ... 

I was able to successfully compile AppleALC and Lilu and started poking around the ALC892 directory. I realize that layout1.xml and layout4.xml are nearly identical (except for the LayoutId) and the real differences between them are in the PlatformsT.xml used for layout 1 and PlatformsM4.xml used for layout4.xml ... I also notice that the patch[0] is different than patch[3] - I am assuming that each layout needs the layoutXX.xml, the PlatformsXX.xml and a patch according to the info.plist 

Any idea how can I generate a new layout that contains mostly "layout1"  but corrects the microphone issue? I don't really care much about the other jacks, but when carrying a laptop around it is really important to have the microphone and the speakers to work. I have to add that I have absolutely no idea what the contents of the layout files are, and even less what the contents of the platform files are... 

The other thing is that after waking from sleep, AppleHDA dies on an assertion, but I have not tried the methods suggested in the blogs to fix it because I have other issues with sleep... 

Thanks very much for your help!

**Comment by vandroiy2013** [comment]
Hi. Try another layout-id's from WiKi [https://github.com/vit9696/AppleALC/wiki/Supported-codecs](url)

**Comment by telicha** [comment]
Thanks! I tried ALL of them - 1 (best, but still needs external mic), 2, 3, 4 (mic works but no output), 5, 7, 92, 99 ... none of them works at least with the speakers and internal microphone ....

**Comment by vandroiy2013** [comment]
So you should build your custom resources. We didn't do this here. We just add existing resources. Issue closed until you provide working resources for your laptop with free layout-id based on Rules for adding resources from FAQ https://github.com/vit9696/AppleALC/wiki/Adding-codec-support

**Comment by telicha** [comment]
Could you point me to some place I can get help into creating the xml files? Thanks

**Comment by vandroiy2013** [comment]
Sorry. I don't know((( @Mirone retired some days ago. Try AppleALC topic on insanelymac.com
