### ISSUE TITLE
Lenovo ThinkCentre M800 - ALC662v2. Internal Speaker and Rear Jack not working

### ISSUE THREAD

**Issue by stich86** [vit9696/AppleALC#159]
Hi,

I'm using AppleALC (ALC662) with a Lenovo M800. Front head-phone/mic works without issue, but not the internal speaker and the rear ports. Any hints?
I'm attaching codec dump from Linux where speakers works.

[codec0.txt](https://github.com/vit9696/AppleALC/files/942603/codec0.txt)

Thanks

**Comment by vandroiy2013** [comment]
Did you try all layouts for this codec? Sorry we don't make resources here we just add existing ones. Try to ask help with patching for your PC on insanelymac.com.

**Comment by stich86** [comment]
I've created my own layout (12 and changed also on Clover).. built new AppleALC.kext but not working (missing audio now). How to debug AppleALC?
Thanks

**Comment by vandroiy2013** [comment]
https://github.com/vit9696/AppleALC/wiki/Installation-and-usage

**Comment by stich86** [comment]
ok, it seems to work now.. attach the two platform\layout and PinConfig.kext's Info.plist
how to do a merge?

It's necessary to use layout-id 12 and it's for ThinkCentre M800 with internal speaker installed.

thanks!

[Resources.zip](https://github.com/vit9696/AppleALC/files/946390/Resources.zip)

**Comment by vandroiy2013** [comment]
OK  I'll add it later today.

**Comment by vandroiy2013** [comment]
Added
