### ISSUE TITLE
Asus z170-pro d3 - Audio not working after installing CUDA

### ISSUE THREAD

**Issue by oluismoreira** [vit9696/AppleALC#160]
Hi,

(I've posted this on tonymacx86 and Toleda told me to "Post to AppleALC developer)

So, I'm a happy owner of a Hackintosh for one year now and I'm trying to install Mac OS on a friend's computer.
The specs aren't the same and that's the issue.

The build:
-6700k
-Asus z170-pro d3
-Asus GTX 980Ti
-Gskill 32GB ram (4x8GB)
-EVO 250GB for OS and Apps
-2x 1tb HDD in raid0

So, here's what I've done so far:

1- Create Mac OS Sierra installer through Unibeast

2- Bios Settings:
     -Extreme Tweeker
        --AI Overclocker Tuner > X.M.P.
        --Extreme Tweeking > Enable
     -Advanced Items
        --System Agent (SA) Configuration > VT-d > Disable
        --PCH Configuration > IOAPIC 24-119 > Disabled
        --USB Configuration > Legacy USB Support > Auto
        --USB Configuration > XHCI Hand Off > Enabled
        --APM Configuration > Power on by PCI - E/PCI > Disabled
     -Boot Menu
        --Fast Boot > Disabled
        --Boot Logo Display > Disabled
        --Secure Boot > OS Type > Other OS
        --Boot Option 1 > USB installer thumb drive (the UEFI choice if there are two entries)

3 - Boot with the Usb stick containing Mac OS Sierra

4 - Install the OS

5 - Boot into the OS (SSD)

6 - Run Multibeast and install the following drivers:

Quick Start — UEFI Boot Mode
Audio — ALC892
Disk — 3rd Party Data
Misc — Fake SMC Plugins v6.21-311-g2958f55.1723
       — FakeSMC HWMonitor Application v6.21-311-g2958f55.1723
Network — IntelMausiEthernet v2.1.0
USB — Increase Max Port Limit

7 - Run CustoMacEssentials to make ethernet work (I don't know why. Just tested it and it worked)

8 - Install Nvidia Web Drivers

9 - Open the Config.plist file with the TextEdit and change the "false" under NvidiaWeb to "true".
     <key>NvidiaWeb</key>
     <true/>

At this point I had three issues:
-No sound (no devices detected)
-The graphics card didn't perform as it should be on the Cinebench. 98fps vs 112fps on my gtx970. I assumed this is an issue with the SMBIOS but I was going to try to fix this later. Help in this point is highly appreciated.
-No USB 3 (haven't tried to fix it yet but I think it will be simple)

I figured out a way to make the sound work through millions of tests but I assume it isn't the right way.
I did this:

1 - Installed AppleALC.Kext through Kext Utility
2 - Copied AppleALC.kext to /VOLUMES/EFI/EFI/Clover/Kexts/Other
3 - Installed HDAEnabler1.kext through Kext Utility

4 - Reboot

5 - Sound working!

Next thing I did was install the Cuda drivers so I could benefit from The Cud acceleration inside premiere pro, after effects, davinci resolve, etc.

Reboot....

No sound again.

And this is where I'm stuck.
I tried to do a clean install but when I get to this point the same happens.

Do you know what might be causing this? Maybe there's another way to make the sound work?

I've included in this post my config.plist plus the AppleALC.kext.
[2files.zip](https://github.com/vit9696/AppleALC/files/946765/2files.zip)

Thank you for your help and patience.

**Comment by vandroiy2013** [comment]
Make clean install of macOS. Don't use any multibeast audio features. AppleALC.kext and Lilu.kext should be ONLY in EFI/Clover/Kexts and NOT in S/L/E or L/E!!! It is important!!! Don't use any HDAEnablers!!! Layout-id should be specified in clover config.plist

Important!!
1. Your AppleHDA.kext MUST be clean (vanilla)
To check if it so use terminal and copy/paste this command
codesign --verify --no-strict /System/Library/Extensions/AppleHDA.kext/
It should show nothing. If not - restore vanilla AppleHDA.kext
2. HDEF section in your DSDT (or clover fix AddDTGP_0001->True and FixHDA_8000->True)
3. Layout-id specified in your DSDT (or clover Audio->Inject) 
4. Remove ALL patches for audio from your config.plist KextsToPatch
5. Remove all DummyHDA.kext from S/L/E or RealtekALC.kext from L/E (if exists) 
6. Remove VoodooHDA.kext and AppleHDADisabler.kext (if exists)

**Comment by vandroiy2013** [comment]
All questions about installation and usage ask in AppleALC topics
In English Insanelymac - http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/page-1 
In Russian Applelife - https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/

**Comment by oluismoreira** [comment]
Thank you! I'm going to try what you suggested with clover since I'm a beginner and I don't know how to mess with the DSDT.

**Comment by vandroiy2013** [comment]
You don't need DSDT at all! Everything you can inject with Clover

**Comment by oluismoreira** [comment]
Hello again, I think I did everything you said and still no devices detected.

_Make clean install of macOS. Don't use any multibeast audio features. AppleALC.kext and Lilu.kext should be ONLY in EFI/Clover/Kexts and NOT in S/L/E or L/E!!! It is important!!! Don't use any HDAEnablers!!! Layout-id should be specified in clover config.plist

**I copied AppleALC.kext and Lilu.Kext to EFI/Cloer/Kexts/Other_
I tried the default Layout-id which was "1" and later I read somewhere that for motherboards with 3 audio ports it should be used "2" and I tried it also and nothing happened.**


_Your AppleHDA.kext MUST be clean (vanilla)
To check use terminal and copy/paste this command
codesign --verify --no-strict /System/Library/Extensions/AppleHDA.kext/
It should show nothing._
**I ran the command you provided and it showed nothing as it should.**

_HDEF section in your DSDT (or clover fix AddDTGP_0001->True and FixHDA_8000->True)
Layout-id specified in your DSDT (or clover Audio->Inject)_
**I clicked on the two checkboxes and I didn't mess with the value in Audio which was the same as in the config.plist layout-ID.**

_Remove ALL patches for audio from your config.plist KextsToPatch_
**Did that.**

_Remove all DummyHDA.kext from S/L/E or RealtekALC.kext from L/E or from EFI/Clover/Kexts (if exists)_
**No DummyHDA.kext in S/L/E. No RealtekALC.kext in L/E. The only kexts I have in EFI/Clover/Kexts are AppleALC and Lilu.**

_Remove VoodooHDA.kext and AppleHDADisabler.kext (if exists)_
**Didn't exist.**

**Comment by vandroiy2013** [comment]
Once more! If you need help with installation and usage ask it in AppleALC threads on insanelymac.com or applelife.ru. Provide there DarwinDumper and IOReg reports.
This conversation is locked!
