### ISSUE TITLE
MSI GS43VR

### ISSUE THREAD

**Issue by Fma965** [vit9696/AppleALC#163]
Hey,

So i've been on corpnewts discord chat and compeltely followed this guide 3 times
https://www.reddit.com/r/hackintosh/comments/4sil5p/audio_mechanic_old_patchfix_removal_applealc/

but i still can't seem to get my audio working, i have a MSI gs43VR Laptop, it has ALC898 according to the detection software.

My HDEF after patched from HDAS is located at 1F rather than 1B though is that an issue?

I've tried every layout and can get you my config.plist if required.

If i use VoodooHDA it works fine except internal microphone but i would rather use native where possible.

Any advice you can give would be extremely helpful :)

Thanks.

**Comment by Fma965** [comment]
Further more the layout is 

> <01 00 00 00> - this is the preferred layout - and supports a wide range of codecs

**Comment by Fma965** [comment]
I forgot to mention the sound devices show up on almost all layouts, they just don't have any sound come out of them :(

**Comment by Fma965** [comment]
i've just seen you are likely to just close this ticket? who can i speak to request further support with this? the guy with the gs63vr is likely to have the same layout i would imagine, can i provider any further help to get this layout added? i've tried to understand it might self but i'm a windows guy and  kext editing confuses me.

**Comment by vandroiy2013** [comment]
All questions about installation and usage ask in AppleALC threads
In English Insanelymac - http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/page-1
In Russian Applelife - https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/

Provide DarwinDumper and IOReg reports in one of this threads, describe your problem and community will help you.

**Comment by Fma965** [comment]
i've added a reply to the thread with attached things http://www.insanelymac.com/forum/topic/311293-applealc-%E2%80%94-dynamic-applehda-patching/page-72#entry2411345
