### ISSUE TITLE
Please update native support for ALC292

### ISSUE THREAD

**Issue by xiweiweiwei** [vit9696/AppleALC#164]
I test AppleALC.kext in Labtop Thinkpad X240，when using legacy AppleALC， set id=12 or 28，it does not work，but with AppleHDA Patcher v1.8 , sound works perfect, the codecID is set to 3, Supported by Mirone, Please update native support for ALC292 inside AppleALC；

Many Thanks!

http://www.insanelymac.com/forum/files/file/496-applehda-patcher/

**Comment by vandroiy2013** [comment]
All codecs from AppleHDA Patcher was implemented in AppleALC. Check the Codec Support page in WiKi. There is 23 different layouts for ALC269!!!
https://github.com/vit9696/AppleALC/wiki/Supported-codecs

**Comment by xiweiweiwei** [comment]
The ConfigData of CodecID 3 is different from both CodecID 12 and 28，I have checked it already， it is a entirely new data；And Only CodecID 3 is workable in Labtop Thinkpad X240；Please add it as a third choice  for ALC292；
