### ISSUE TITLE
Headphones/Mic plugging not detected

### ISSUE THREAD

**Issue by theclue** [vit9696/AppleALC#165]
Hi!

first of all let me say that your solutions is WONDERFUL! I'm terribly happy I could make my audio working without bloating my S/L/E!

My setup: Realtek ALC892, layout = 1

Said that, dunno if it's an issue or a misconfig, but I was not able to make my front panel (HD Audio) works. Plugging headphones or frantic simply as no effect. Is there any check I can do to investigate further?

tnx for support!
gabriele

**Comment by vandroiy2013** [comment]
AC97 front panel audio don't supported!!! Only HD Audio front panel

**Comment by theclue** [comment]
Hi vandroiy2013,

tnx for your prompt reply. Sorry to mention I'm using the HD Audio end connection of the cable from my case.

The motherboard has one plug

Case: Bitfenix Prodigy
Motheboard; MSI H97i

tnx for support!

**Comment by vandroiy2013** [comment]
Suggest you to try different layout-id's from Compatibility support list for ALC892. https://github.com/vit9696/AppleALC/wiki/Supported-codecs  It's an ITX board so maybe there is different node sequence. In worst scenario you will need custom resources for this board!!!
