### ISSUE TITLE
GA-B250M-D2V ALC887 not work

### ISSUE THREAD

**Issue by snopein** [vit9696/AppleALC#166]
layout 1, 2, 3, 5, 7, 11, 13, 17, 18, 33, 99 all try still not work
i use GA-B250M-D2V 
1,2,3 can see the ouput device but no sound

**Comment by snopein** [comment]
shuld i enable the ACPI HDA or FixHDA_8000 ?

**Comment by vandroiy2013** [comment]
ALC887 is confirmed 100% working. Even on 200-series. If you need help ask for it in AppleALC threads on applelife.ru or insanelymac.com. 
Russian - https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/
English - http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/
