### ISSUE TITLE
CX20751/2

### ISSUE THREAD

**Issue by dekisugi123** [vit9696/AppleALC#167]
Perfect recognization, but the input doesn't receive any sound :?

**Comment by vandroiy2013** [comment]
Try another layout-id for your codec.
https://github.com/vit9696/AppleALC/wiki/Supported-codecs

If you have problems with resources ask for help in AppleALC thread on insanelymac.com
http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/

**Comment by dekisugi123** [comment]
I mean, both layout id dont help. It can detect the audio input, just can't receive the sound to micro

**Comment by vandroiy2013** [comment]
Ask for help with custom resources on insanelymac.com in AppleALC thread. Different laptops have different node sequences.

**Comment by dekisugi123** [comment]
No one helps me. Can you suggest me to do anything so I can fix it up myself? Any guide to read?
