### ISSUE TITLE
Codec request - ALC271x with Layout_ID = 13 support

### ISSUE THREAD

**Issue by mochadwi** [vit9696/AppleALC#171]
Unfortunately, on **_Acer Aspire V5-471G (Laptop)_** my audio **layout_id = 13**, still doesn't have support for _**AppleALC**_. Please, if you kind enough to add support for **layout_id = 13**. If you need anything particular I can do to help or contribute just mention me here.

**Comment by mochadwi** [comment]
If you guys need similar files for troubleshooting. I can refer you [here](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/ALC271x.zip) from @insanelydeepak

**Comment by vandroiy2013** [comment]
ALC271x = ALC269. Use layouts from WiKi https://github.com/vit9696/AppleALC/wiki/Supported-codecs for ALC269
