### ISSUE TITLE
No sound on Mavericks

### ISSUE THREAD

**Issue by ammoune78** [vit9696/AppleALC#172]
Hi, i don't have sound on mavericks, but Sierra and other OS X versions are ok.

Config:
Mobo: GA-Z97M-DS3H-F7 Rev:1.1
Chip: Realtek ALC887 
Audio Device: 0X80868CA0
Codec ID: 0x10EC0887
Subsystem ID: 0xA1820000
Subsystem Vendor ID: 0x14580000
Revision: 0x0302
Layout ID used: 1, Toleda 
PinConfigurations: 0xf0 0x11 0x11 0x41 0x10 0x40 0x11 0x90 0x20 0x10 0x01 0x01 0x30 0x60 0x01 0x01 0x40 0x90 0xa0 0x90 0x60 0x90 0x81 0x02 0x50 0x30 0x81 0x01 0x70 0x40 0x21 0x02 0xf0 0x11 0x11 0x41 0x01 0xc6 0x24 0x40 0x90 0x61 0x4b 0x01

Please i need help for it to work

**Comment by vit9696** [comment]
Please check that AppleALC is loaded on 10.9 e.g. by running it in -alcdbg mode and checking if there is anything in the log (see the wiki). If it is, and the patches are applied, you should ask Toleda or other people regarding what patches are needed for 10.9.
