### ISSUE TITLE
No sound/ incorrect Port Detection  Intel DG41RQ with ALC662

### ISSUE THREAD

**Issue by kdhingra307** [vit9696/AppleALC#173]
Hi,

Thanks for your wonderful work, I got the same problem as was in issue #80 . Tried my best to resolve it on my own. But couldn't (new to Macintosh). Any help would be wonderful

My specs:
CPU: Intel Xeon X5450 @3GHz
MoBo: Intel DG41RQ
RAM: 8GB @ DDR2 800MHz
Graphic: Gigabyte GT710
Audio Codec: ALC622
Audio Controller:  NM10/ICH7 Family High Definition Audio Controller

I am currently fiddling with layout 5. Tried all already.

I am getting device listed but incorrect mapping, also I am getting no sound from same.

I am getting error missing controlModInfo for @0u controller, but my controller should be in AppleHDA (using Vanilla One).

Attaching Screenshots for reference

![](https://cdn.discordapp.com/attachments/250798964549484545/319184930921775104/Screen_Shot_2017-05-30_at_11.45.51_AM.png)

![](https://cdn.discordapp.com/attachments/250798964549484545/319185184824098816/Screen_Shot_2017-05-30_at_11.47.27_AM.png)

![](https://cdn.discordapp.com/attachments/250798964549484545/319185675331174400/Screen_Shot_2017-05-30_at_11.49.06_AM.png)

![](https://cdn.discordapp.com/attachments/250798964549484545/319185690086735873/Screen_Shot_2017-05-30_at_11.49.10_AM.png)

I forgot to store debug log during this boot, if u want can attach it further on.

**Comment by kdhingra307** [comment]
Was closed by mistake

**Comment by vit9696** [comment]
Hi, your controller is supported, so it is not an issue. You are using an ancient version of AppleALC, please update to the recent one and try all the layouts. If it does not work, reach for codec requests on the forums, we do not make the resources here.
