### ISSUE TITLE
Audio devices are in spanish.

### ISSUE THREAD

**Issue by puffpants** [vit9696/AppleALC#174]
Ive used the newest version of applealc 

![screen shot 2017-06-14 at 7 15 31 pm](https://user-images.githubusercontent.com/963134/27159056-80e3f9d4-5138-11e7-8ac5-c9f3d40ade10.png)

**Comment by vit9696** [comment]
You have corrupted AppleHDA.

**Comment by puffpants** [comment]
i extracted it from the 10.12.5 combo update...
