### ISSUE TITLE
ALC887 (хрипит на максимальной громкости)

### ISSUE THREAD

**Issue by enjoyharddrink** [vit9696/AppleALC#177]
Здравствуйте.
Звук хрипит(как перегруз) на максимальной громкости.
Mac OS Sierra 10.12.5
Realtek ALC887
Gigabyte ga-b250m-ds3h
Intel Pentium g4560
Пробовал только через выход на материке. Та же проблема была в windows 10, но после установки драйвера Realtek с сайта Gigabyte такой проблемы не было.
(Пробовал все layout-id). Заранее спасибо ;)

**Comment by vit9696** [comment]
Привет, могу посоветовать искать ресурсы, которые хрипеть не будут. Всякие патченные AppleHDA и так далее. Если найдёшь, то без проблем добавим.
Кстати, можно попробовать Voodoo. Он не хуже.
