### ISSUE TITLE
Sound volume issue for ALC 282 on Sierra 10.12.5

### ISSUE THREAD

**Issue by Lezardon** [vit9696/AppleALC#178]
Hello

I have installed AppleALC + Lilu on a laptop Dell Inspiron 15 3521 running dual boot Sierra 10.12.5+Windows 10.
The sound volume from internal speakers is only the half from the sound I get from the Windows 10 session.However, the sound from jack port is very good.
How can i get a normal sound volume from the internal speakers?

Thank you. Attached is my ioreg.

**Comment by Generation88** [comment]
@Lezardon What Layout ID you are using...try using 29

**Comment by Lezardon** [comment]
I have tried several layout: 3, 13, 28, 29, 86... without any result :(

**Comment by Generation88** [comment]
mine is working extremely fine

**Comment by Lezardon** [comment]
Oh I'm jealous :) It makes several weeks I'm spending my free time on this issue. May I know a little bit about your hardware and config, so I can explore what is wrong on my config ? Are you using Sierra 10.12.5 ? do you have a config.plist/ioreg to show me for my investigations ?

**Comment by Generation88** [comment]
ye i do have dell inspiron 3521 & i am using sierra 10.12.5

**Comment by Generation88** [comment]
send me your efi folder

**Comment by Generation88** [comment]
lemme have a look

**Comment by Lezardon** [comment]
Thanks :) Can u send me your email ?

**Comment by Generation88** [comment]
here it is: oopsgeneration88@gmail.com

**Comment by Lezardon** [comment]
Could you make a favor ? i have aproblem in compiling with Xcode. Could you send me the ALC kext you are using ? Thank you so much.
