### ISSUE TITLE
ALC 668 on ASUS ROG G752 VM 10.12.5

### ISSUE THREAD

**Issue by darkuser89** [vit9696/AppleALC#179]
Hello 

i have AppleALC on my ASUS ROG G752VM with 10.12.5 installed.

ID = 3
Intern Speaker Left and Right  = Works
Intern Subwoofer = No Works
Intern Mic = Works
Extern headphone = No Works
Extern Mic = No Works
Line-In = No Works

ID=20
nothing works

ID = 28
Intern Speaker Left and Right = Works
Intern Subwoofer = Works
Intern Mic = Works
Extern headphone = No Works
Extern Mic = No Works
Line-in = No Works

ID = 29
Intern Speaker Left and Right = Works
Intern Subwoofer = No Works
Intern Mic = Works
Extern headphone = No Works
Extern Mic = No Works
Line-in = Works

Have voodoohda tested and all outputs and inputs works.
You can dump it and install it in the AppleAlc?

**Comment by vit9696** [comment]
If VoodooHDA works fine for you, why would you want AppleALC? Also, we do not make the resources here.
