### ISSUE TITLE
ALC 295 Asus UX430UA 10.12.5, 10.12.6

### ISSUE THREAD

**Issue by gulios** [vit9696/AppleALC#180]
Hi,  

Laptop: Asus UX430UA
CPU: i7-7500U
Audio: ALC295
Audio device: 0x80869D71
Sub Device: 0x10431740
Codec ID:0x10EC0295
Revision: 0x0002

I'm trying to use newest AppleALC.kext and there is very strange issue.
I've tried AppleALC and Lilu kext and inject 28 in clover config.plist
Audio devices are visible in System Preferences, microphone works(tested via facetime), changing sound level works, changing output device works but there is NO sound from speakers and headphones ;(

I've tried inject 13 and 1 but only with 28 audio output is availabe in system preferences.
There is more details on https://www.tonymacx86.com/threads/solved-realtek-alc295-audio-crackling-after-wake-from-sleep.215742/page-2#post-1537135

For now i'm using patched AppleHDA(broken headphones) but i it's not good situation and it;s much better to use your kext instead of modyfied S/L/E.

Thank you

**Comment by vandroiy2013** [comment]
Added. 
https://github.com/vit9696/AppleALC/commit/d49edbd6e46f961ec7cfd09b2bbee52cc1260d70
Here is prebuild binary. 
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/1125658/AppleALC.kext.zip)
Use layout-id 3 and codec commander.

**Comment by gulios** [comment]
Thank you sound works great on speakers, so i don't need to change S/L/E great ;) 
but there is still problem with sound on headphones,  it's cracklikng(sound distorted).
Same issue as via hda patcher ;(

Is it possible to fix it ? I use most speakers but it would be great to have 100% working audio ;)

anyway, thank you again for that !

**Comment by vandroiy2013** [comment]
Sorry. I just add @Mirone resources. We didn't make resources here.
