### ISSUE TITLE
No HDMI audio, Haswell 4500u, ALC288, HD4400

### ISSUE THREAD

**Issue by macmeister1967** [vit9696/AppleALC#181]
Thanks for great software, working sweetly with latest AppleALC and lilu kexts...

I am also using FakePCIID_Intel_HDMI_Audio.kext to try and fix this, to no avail...

Laptop sound out/in works great (Aspire V5-573), just no HDMI out :-(

My BOD3 is in SSDT-5.aml

it is device 0a0c which is supported by FakePCIID_Intel_HDMI_Audio.kext (supposedly).

I have patched DSDT and SSDT-5 with RM,DeviceID= (for 0a0c device)... still no output showing 👎 

Any help greatly appreciated!

**Comment by vandroiy2013** [comment]
Read here http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/?p=2450475
