### ISSUE TITLE
error for compiling

### ISSUE THREAD

**Issue by sandyplus** [vit9696/AppleALC#182]
Three errors find in AppleALC compiling. All of them are related to the kern_start.cpp.
The error shows "Use of undeclared identifier 'arrsize'".
I modified these code to the previous version, and it works fine.
`      arrsize(bootargOff), -->sizeof(bootargOff)/sizeof(bootargOff[0]),
	arrsize(bootargDebug),-->sizeof(bootargDebug)/sizeof(bootargDebug[0]),
	arrsize(bootargBeta),-->sizeof(bootargBeta)/sizeof(bootargBeta[0]),
`

**Comment by vandroiy2013** [comment]
There were changes in Lilu and AppleALC. Compile latest Lilu and add it in AppleALC folder
