### ISSUE TITLE
A new working ALC236 codec

### ISSUE THREAD

**Issue by rexx0520** [vit9696/AppleALC#183]
With layout 11 in vanila 1.1.3, my ALC236 plays perfectly but the mic didn't work.
This is the file which i'm using with layout 3. 
ALC236 plays perfectly with both speakers and mic.
But i modified it a long time ago that i forget everything about AppleALC..
I hope to make my ALC236 working perfectly with the latest release..thanks.
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/1144512/AppleALC.kext.zip)

**Comment by vit9696** [comment]
We will add this as `layout-id` 13. Please do not forget the source code next time. While it is possible to extract the resources, I may not be kind enough to do it the other time.
Please provide your laptop model for a cleaner name.

**Comment by rexx0520** [comment]
The model name is Lenovo Xiaoxin Air 13 Pro
I'm appreciate with it,thank you!

**Comment by vandroiy2013** [comment]
Added. Test it. Report.

**Comment by rexx0520** [comment]
It works. Thank you.

**Comment by volcbs** [comment]
Just want to say to @vandroiy2013 that it works in Lenovo IdeaPad 510s too using layout-id 13
