### ISSUE TITLE
Conexant CX20755 not working on Sierra 10.12.6?

### ISSUE THREAD

**Issue by remi6397** [vit9696/AppleALC#186]
Good evening everybody,
I've successfully used AppleALC on 10.12.5 for this codec, but after the latest update, it doesn't detect any devices.

### Essential logs:

**Codec**
Conexant CX20755 (from specification)

**Device**
```
$ ioreg -rxn IOHDACodecDevice 
+-o IOHDACodecDevice@1B,0  <class IOHDACodecDevice, id 0x10000032d, !registered, !matched, active, busy 0, retain 5>
    {
    }
```

**.kext**
```
/Volumes/EFI/EFI/CLOVER/kexts/10.12/ACPIBatteryManager.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/AppleALC.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/AppleBacklightInjector.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/AtherosE2200Ethernet.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/DirectHW.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/FakePCIID.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/FakePCIID_Intel_HD_Graphics.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/GenericUSBXHCI.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/Lilu.kext
/Volumes/EFI/EFI/CLOVER/kexts/10.12/VoodooPS2Controller.kext
/Volumes/EFI/EFI/CLOVER/kexts/Other/FakeSMC.kext
/Volumes/EFI/EFI/CLOVER/kexts/Other/FakeSMC_ACPISensors.kext
/Volumes/EFI/EFI/CLOVER/kexts/Other/FakeSMC_CPUSensors.kext
/Volumes/EFI/EFI/CLOVER/kexts/Other/FakeSMC_GPUSensors.kext
/Volumes/EFI/EFI/CLOVER/kexts/Other/FakeSMC_LPCSensors.kext
```

**Clover's config**
Attachment: [clover.plist](https://github.com/vit9696/AppleALC/files/1160406/clover.plist.txt)

_Thank you for any kind help!_

**Comment by vit9696** [comment]
I am pretty sure this is possible, but I am afraid we cannot really help you. If you contact the developer of those resources, he might give you a hint.

**Comment by remi6397** [comment]
I still think it might be issue with AppleALC, because after reinstalling I
observed, that sound works randomly, on about one of three boots. Also, I
want to add that I compiled Lilu and AppleALC from git, and it didn't
helped in my case. Anyways, I'll be trying to contact the developer of this
specific implementation.

23.07.2017 18:31 "vit9696" <notifications@github.com> napisał(a):

**Comment by vit9696** [comment]
Are you sure you have AppleALC and Lilu installed in EFI and AppleHDA is ok?
There is a similar bug here: https://github.com/vit9696/AppleALC/issues/176.
Do you have AppleALC loaded when there is no sound?

I think I had a few other reports like that, and the issue was something confusing in ACPI.

**Comment by remi6397** [comment]
I'm sure that AppleHDA is Vanilla and all kexts are in Efi partition. Before 10.12.6 there weren't any problems on the same configuration. Kextstat output is the same in both cases. AppleHDA is loaded after AppleALC and Lilu.

**Comment by vit9696** [comment]
Well, mhm. I have AppleALC here on 10.12.6, as well as some other people, and it works just fine. So I am afraid the issue is very specific to your codec :(.

Could you try taking the AppleALC resources and manually patching AppleHDA to see if the issue is exists in this case as well?

**Comment by remi6397** [comment]
On my desktop computer AppleALC works too. So, as 10.12.6 brought some changes in audio system, maybe it really means, that patches are incompatible? But, on the other side, it works from time to time…

**Comment by vit9696** [comment]
I am unaware about any changes in 10.12.6, in fact you are the first one. Let me know if you get more details.

**Comment by eitanlevy97** [comment]
Actually I encountered the same problem yesterday that the IOHDACodecDevice remains empty. Mine is 10.13.2. It was happend suddenly and I have no idea what to do now. Missing codec information makes AppleALC unable to determine the proper configuration to load.

Are there any hooks inside AppleALC that allow us specify a codec-id rather than read from IOKit?

**Comment by remi6397** [comment]
@eitanlevy97, did it break after some update?

**Comment by eitanlevy97** [comment]
@remi6397 No. I am still investigating the reason and workaround..

**Comment by eitanlevy97** [comment]
@remi6397  Problem solved for me by reviewing HDEF section in SSDT/DSDT.
