### ISSUE TITLE
No output sound MSI Z270 Gaming Pro Carbon, OS X 10.11.6

### ISSUE THREAD

**Issue by SlyFoxeh** [vit9696/AppleALC#188]
Trying to launch sound on that mono with 10.11.6 and 1.1.3 version of AppleALC.kext, but with trying layouts 1,2,3,5,7,11 - got nothing. Got working line in like a charm, but output devices doesn't play any sounds at all.

**Comment by vit9696** [comment]
That's very annoying, but I am afraid not much could be done until you contribute the compatible resources for your codec.
