### ISSUE TITLE
Weird device names on 10.12.6 (but it's working)

### ISSUE THREAD

**Issue by niklaswa** [vit9696/AppleALC#189]
![n8cdvxob](https://user-images.githubusercontent.com/7442307/28479540-1d4de064-6e5d-11e7-815d-9928f9b5046d.png)

Build:
![4lxuaujk](https://user-images.githubusercontent.com/7442307/28479573-46aef740-6e5d-11e7-9634-703758ea715f.png)

Hardware:
Motherboard: ASUS MAXIMUS VIII HERO
CPU: Intel® Core™ i7-6700K
GPU: MSI GEFORCE® GTX 970 GAMING 4G

Kextstat:
https://pastebin.com/raw/Up4H0afW

**Comment by vandroiy2013** [comment]
Your AppleHDA.kext is corrupted. Replace it.
