### ISSUE TITLE
ALC659-CG support?

### ISSUE THREAD

**Issue by MoreRobustThanYou** [vit9696/AppleALC#207]

**Comment by edward-p** [comment]
Search `Resources/PinConfigs.kext/Contents/Info.plist`

**Comment by MoreRobustThanYou** [comment]
it's not there, how would I add it? I can't find ANY info on it online.

**Comment by MoreRobustThanYou** [comment]
i dont understand how to port it @vit9696  and there's no info online on it

**Comment by edward-p** [comment]
First you should know that AppleALC is just a tool to patch AppleHDA dynamically. To add support to your card you should know how to patch AppleHDA at first. See [AppleHDA Patch Guide](http://forum.osxlatitude.com/index.php?/topic/1946-complete-applehda-patching-guide). When you're ready start at [Adding-codec-support](https://github.com/vit9696/AppleALC/wiki/Adding-codec-support)
