### ISSUE TITLE
X299 1220A Asus Prime Deluxe 

### ISSUE THREAD

**Issue by xxrobdogxx** [vit9696/AppleALC#208]
I have tried to get the 1220A codec working with no luck
I have renamed CAVS to HDEF. Now HDEF appears in IOReg however no audio
After looking in the Pinconfig kext I have noticed there isn't a profile for X299 boards
Has there been any progress with this X299 platform? What should I do now?

Regards

**Comment by vandroiy2013** [comment]
First of all you have to fake your unsupported audio controller with supported device-id. Then test it in Clover config.plist. And after i will add this patch into AppleALC.kext.

**Comment by xxrobdogxx** [comment]
Could you please tell me how to do this? Do I just use a device ID from one of the supported ones? But 1120A is already supported, it just doesn't work on X299

**Comment by vandroiy2013** [comment]
This is NOT support topic!!! 
And you need to fake Audio controller ID and not Audio codec ID!!!
![2017-10-09 16 18 32](https://user-images.githubusercontent.com/8144780/31340030-8a332894-ad0d-11e7-95d6-2edfc75d2646.png)
