### ISSUE TITLE
Use AppleALC without DSDT?

### ISSUE THREAD

**Issue by grandosegood** [vit9696/AppleALC#210]
Hi there,

I setup a hackintosh according to Rampagedev's Guide, which uses SSDT files in EFI/ACPI/patched rather than DSDT. can i still use these kexts and the clover ACPI patch? thanks

**Comment by grandosegood** [comment]
Hi there, why was the thread closed? Is there an answer to my question?
Thanks for your time.

**Comment by 1and1get2** [comment]
You can use clover layoutid injection, or you could always do some research before ask
