### ISSUE TITLE
VIA VT2020/2021 for Layout-ID: 9

### ISSUE THREAD

**Issue by revunix** [vit9696/AppleALC#213]
Hello

GA-Z77X-D3H needs layout-id: 9
This is a patched [AppleALC.kext](https://github.com/vit9696/Lilu/files/1378621/AppleALC.kext.zip) i don't know what the guy has changed but it works. 

@vit9696 please add the support for id: 9 this will be nice :) 

[German Source](https://www.hackintosh-forum.de/index.php/Thread/29822-VIA-VT2020-2021-Z77X-D3H-mit-DSDT-Patch/)

**Comment by vandroiy2013** [comment]
Added. Try it. Report. 
Layout-id 9
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/1385066/AppleALC.kext.zip)

**Comment by revunix** [comment]
Works!

**Comment by nickw444** [comment]
Hey @revunix thanks for this – Which revision of the mobo is this for? I have a Rev 1.0, but this doesn't seem to work for me.

**Comment by revunix** [comment]
hmm, i have Rev 1.1 maybe use ID: 5 or 7
