### ISSUE TITLE
Kernel panic 

### ISSUE THREAD

**Issue by piiiggg** [vit9696/AppleALC#214]
Hi, I got this problem yesterday after 4/10 times I tried to boot up my hackintosh but it self-reboot about 80% of Apple loading bar. 

This is why happen when I tried to capture kernel log with my iPhone using slo-mo mode
https://photos.app.goo.gl/zB1y5uv0pn1pa7y73

You can see here https://photos.app.goo.gl/fnWteICxGuIcBIWo1 it's said 
kernel extensions in backtrace:
as.vit9696.Lilu and AppleALC

My system: macOS 10.13 17A405
ASRock H110M-G/M.2
i3-7100
GT1030

**Comment by vit9696** [comment]
Well, add keepsyms=1 at least and make a clearer photo with both the top of the panic and a stack trace. I will see what I can do. Ideally you get me a plain text panic report of course, but I guess it is not really possible if you do not have working nvram.

**Comment by piiiggg** [comment]
I don't understand what is NVRAM but I think it's working because I can boot into my system with Nvidia web driver, also keepsyms=1 is not working on High Sierra, I tried it. So I switch to 720p with more fps than the last time. Also, I still can boot with -x command

https://photos.app.goo.gl/3FIECf9MQN7h2t2s2

**Comment by vit9696** [comment]
From what I know keepsyms=1 works just fine in 10.13, you might be doing something wrong. Perhaps you tried it with non-debug versions of Lilu and AppleALC.

Also, -x disables audio drivers, so no surprise it "works".

**Comment by piiiggg** [comment]
I still erase my macOS partition for re-install tomorrow, if AppleALC and Lilu still working I'll close this issue. If not I'll try the debug version

**Comment by piiiggg** [comment]
After re-install, my system working not normally. Maybe the problem from my system, sorry !
