### ISSUE TITLE
ALC298 no speaker, noise on headphone

### ISSUE THREAD

**Issue by maltegrosse** [vit9696/AppleALC#215]
Dear All,

I got a Lenovo x270 (10.3, i5 - 7200u) and the kernel recognize the soundcard on ID 13. but there is silent on the speakers, and and some noisy playback on headphone. 

here my dump - any suggestions?

https://pastebin.com/q10GG7SZ

**Comment by bt** [comment]
Having the same issue; any ideas why this was closed?

**Comment by maltegrosse** [comment]
solved here 
http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/?p=2520862
