### ISSUE TITLE
Help me Add New Code for ALC270

### ISSUE THREAD

**Issue by razerfanboy** [vit9696/AppleALC#218]
I have successfully patched AppleHDA on the Asus S46CM using the ALC270. I have found a way to Add New code but English is hard for me. I attached the data that I obtained. Hope it will be on your project the very last day. Thanks you so much!
[ALC270 Asus s46cm.zip](https://github.com/vit9696/AppleALC/files/1393291/ALC270.Asus.s46cm.zip)

**Comment by hellohasbi** [comment]
Hi Sir, I see your attached file. How to create platform.xml.zlib and layout.xml.zlib?
Thanks!

**Comment by razerfanboy** [comment]
You can create platform.xml.zlib and layout.xml.zlib from platform.xml and layout.xml through the HDA Wizard.app
[HDA_Wizard_ML.zip](https://github.com/vit9696/AppleALC/files/1444959/HDA_Wizard_ML.zip)

**Comment by hellohasbi** [comment]
I've ALC270 too, but headphone not work with Original layout ID 3,4,27,28..
But I tried to create my own AppleALC with lilu, and I my system restart, when go to SysPref>Audio>Input, and then I try to used your Platform.xml.zlib and LayoutID.xml.zlib, Input and Output worked perfect, include with Headphone.
Now I tried to create my own too for Platform and LayoutID. 💃 

Thanks for your work.

**Comment by razerfanboy** [comment]
:)congratulations

**Comment by vandroiy2013** [comment]
Closed until you provide resources with layout-id not present in AppleALC for your codec. You have to test chosen layout-id before. It should looks like this request. 
![screen shot 2017-11-10 at 11 04 57 am](https://user-images.githubusercontent.com/8144780/32650596-1591fad4-c607-11e7-8677-5ba8e45dc046.png)
