### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by desert0616** [vit9696/AppleALC#227]
Thanks for the wonderful work!

I recently get a panic after a manual restart. Before this error appears, my system works well including sound. So I am puzzled about what happened between last successful boot and current. The only related operation may be that I switch the output device between a USB soundbar and a headset. Will it effect?

The error message appears and rolls over fast so that it is not easy to capture a clear photo to show the exceptions. Do you have any comments about it? Thanks so much.

![wx20171115-145244](https://user-images.githubusercontent.com/13389038/32826084-042f7c3e-ca22-11e7-972e-2848ab9b5cf0.png)

**Comment by vit9696** [comment]
Please update your issue with more details: https://github.com/vit9696/AppleALC/commit/adc7f47ebfa5d56becdee5179376db9443fb8cc5
