### ISSUE TITLE
Codec enters a low-power state on idle (High Sierra)

### ISSUE THREAD

**Issue by sirburpalot** [vit9696/AppleALC#237]
I'm using the latest versions of Lilu and AppleALC on an ASUS Z170I motherboard, which has the ALC1150 audio codec, with iMac17,1 as the system definition and 1 as the layout ID. AppleALC worked fine for me on Sierra, but after I upgraded to High Sierra, I noticed that sound would often disappear after a period of inactivity. I checked the logs in Console.app, and from the looks of it, this is because of macOS putting the codec in a low-power state (I should also add that my motherboard has an EAPD). From what I've read on the applelife.ru forums, this only occurs when iMac is used as a system definition, and AppleALC is supposed to have a workaround for this (this must be what the AFGLowPowerState key is for in Info.plist), but for some reason, the workaround no longer works for me. Setting AFGLowPowerState to false in Clover does not do anything, either. Nor does the CodecCommander kext do anything to fix the problem, because it only reinitialises the EAPD after the system wakes up from sleep.

Is there anything that can be done to fix this? If there's any other information that you need, I'll be happy to provide it.

**Comment by vandroiy2013** [comment]
Add CodecCommander.kext. ResetHDA and AFGLowPowerState is not enough for ALC1150
This CodecCommander.kext with special fixes for ALC1150

[CodecCommander.kext.zip](https://github.com/vit9696/AppleALC/files/1526886/CodecCommander.kext.zip)

Report back.

**Comment by sirburpalot** [comment]
No, that doesn't seem to have done anything - the codec still enters a low-power state, and I still get no sound when it comes back from it.

**Comment by sirburpalot** [comment]
By the way, putting the system into sleep and then waking it up does trigger CodecCommander and temporarily bring sound back, but then it just disappears once again after a period of inactivity.
