### ISSUE TITLE
[ALC255] Internal Microphone stopped working

### ISSUE THREAD

**Issue by Genxster1998** [vit9696/AppleALC#247]
# ALC255 OR DELL 3234 REALTEK AUDIO 
OS:Mac OS ver 10.12.2 Sierra
Machine:Dell Vostro 3546 similar config to Inspiron 3542

Right from beginning ,audio jack microphone _aka_  line in is not working but **Internal Microphone**  is working in **July**  build of Applealc ,today i switched to latest build and **internal microphone**  is detected but not working for both layout id **13**  and **17** .
However ,**Speakers**  (Internal+Jack)from both builds working fine.

_Sent from my Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vandroiy2013** [comment]
@Genxster1998 
You should ask @insanelydeepak about changes he made. 
https://github.com/vit9696/AppleALC/commit/218a9c6422ddab35fc91deea02fafaeaa6e9d309

And again! This is not support forum!
