### ISSUE TITLE
[ALC255] Asus X441UV ( Headphones work!!, but speakers not working )

### ISSUE THREAD

**Issue by alfinauzikri** [vit9696/AppleALC#248]
macOS High Sierra 10.13.3
Laptop Asus X441UV
Codec : ALC255

Well before, i have installed the latest **AppleALC.kext** (**1.2.2**) using **layout-id 3**, **noise** problem and speaker not working also in all **layout-id**. Then i tried **layout-id 27** it worked, when i inserted **headphones** into **audio jack**. but the problem is **Speakers** that still does not work in **layout-id 27**.

Thanks*

**Comment by Genxster1998** [comment]
@alfinauzikri
For Alc255 ,try layout id 13 and 17 ,layout id 3 cause abrupt high cpu usage 

_Sent from my Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vandroiy2013** [comment]
@Genxster1998 
Layout-id 3 was fixed almost a year ago
https://github.com/vit9696/AppleALC/commit/16f5afc3aaa3368bdb9c22dd60d53e318df6a3d5
