### ISSUE TITLE
The new version of the compiler is error

### ISSUE THREAD

**Issue by melxman** [vit9696/AppleALC#249]
Today,i has builded the NO. a7ab1b7 with clean source,Xcode has Compiled successfully。
But if i has Archived that，error is『
Showing Recent Issues
/Users/hdcat/AppleALC/ResourceConverter/generate.sh: line 22: /Users/hdcat/Library/Developer/Xcode/DerivedData/AppleALC-eeiefithmhmxwncjphshsqdpggso/Build/Intermediates.noindex/ArchiveIntermediates/AppleALC/InstallationBuildProductsLocation/Library/Extensions//ResourceConverter: No such file or directory
』。

Please help

**Comment by vit9696** [comment]
Thank you for your report, this should be fixed by https://github.com/vit9696/AppleALC/commit/1829b2f475e487d3905e43d2f7c9a245380400a2!
