### ISSUE TITLE
Succes add alc 270 layout 10

### ISSUE THREAD

**Issue by ahdan13** [vit9696/AppleALC#259]
[AppleALC-master 3.zip](https://github.com/vit9696/AppleALC/files/1845073/AppleALC-master.3.zip)
Here I'll share about my succes build the alc270 0x0100 using layout id 10. Hope u can share it

**Comment by vandroiy2013** [comment]
Hi
What did you change in this resources? Your revision-id is the same as in trunk. Did you made custom resources for this codec? I will not add unknown stuff in AppleALC without explanations. Provide description of what did you change, why and for what hardware.

**Comment by ahdan13** [comment]
Hi, I just added my Platfrom ALC270 sound for ASUS Laptop, because it not
same with resource in AppleALC file before and not working for me. So I
added it, and It's working to me. Some ASUS Laptop's user use AppleALC from
my Platfrom ALC270 and it's working for them. I asked to you to reupload
the new file who I have added the new platfrom ALC 270 using Layout 10. I
hope u can do it. Thanks
