### ISSUE TITLE
Error when compiled

### ISSUE THREAD

**Issue by gesla** [vit9696/AppleALC#260]
When I compiled the source code，whether modified or not， I got back this error message
![image](https://user-images.githubusercontent.com/34957813/38090547-8a42eb44-3395-11e8-87ed-3373fcbf3e86.png)

**Comment by ahdan13** [comment]
Let's try to upgrade your Xcode Version. That issue can be found cause your Xcode is so low version. Remember, to compile the master AppleALC.xcode must use newer version

**Comment by ahdan13** [comment]
Step 1 = You should be upgrade your Xcode
Step 2 = You should be redownload the Master AppleALC zip from github website (because your file has exposed the format of Xcode old version, so you must redownload
Step 3 = Compile your AppleALC.xcode using newer version of Xcode
Step 4 = Finished

**Comment by vit9696** [comment]
Use Lilu from master. Not from the releases.

**Comment by ahdan13** [comment]
Yesterday, I got same issue, so I upgrade the newer version of Xcode, and it's working for me. For Lilu kext, yu should be added lilu.kext from kext whom build using the master zip of lilu, you can take from github resource. Build that lilu kext, then add on your master Apple ALC folder, and compile it. It's working for me and let's try it
