### ISSUE TITLE
ALC256 layout56 default setting value is 13 in zlib files

### ISSUE THREAD

**Issue by crackself** [vit9696/AppleALC#265]
Hi , guys
I have testing my dell 7559 ALC256 codec driver, here's found [layout56.xml.zlib](https://github.com/vit9696/AppleALC/blob/master/Resources/ALC256/layout56.xml.zlib) include a layoutid value "13", which not match the setting layoutid for Platforms56.xml.zlib(it should be 56).
![56-13](https://user-images.githubusercontent.com/16448332/38451368-1fbe5790-3a61-11e8-896d-45652479f4f7.png)

**Comment by crackself** [comment]
As my test, id=3 work for ALC256 on Dell 7559
I fork and add id=3 [here](https://github.com/crackself/AppleALC/commit/3588206ca83bae82c3e1cf73733a844cbf3d8b19),hope it can help others.

**Comment by vandroiy2013** [comment]
Hello!
This value doesn't matter. It will work even with random values. 
As for id 3 - read the FAQ. Layouts from 1 to 10 reserved for Toleda and Mirone resources.
