### ISSUE TITLE
no hdmi or display port audio

### ISSUE THREAD

**Issue by xelanaiznac** [vit9696/AppleALC#269]
hi vit9696.
i have a Nvidia Pascal 1070, using nvidiagraphicsfixup and applealc latest releases.
the issue is that I have no audio trough cdmi or display port. is it normal due to the lack of gp104 fix in applealc?

**Comment by xelanaiznac** [comment]
edit: solved

**Comment by vandroiy2013** [comment]
Build latest kext manually.
