### ISSUE TITLE
Compiled Kext fails to load

### ISSUE THREAD

**Issue by NextBlaubeere** [vit9696/AppleALC#288]
Hello everyone,

I am currently trying to get a _Creative Sound Blaster Audigy FX_ PCIe Card to work, which has a ALC898 Chip on it. This needs some modifications in the kext which i am trying to do myself though i am not an experienced osx dev.

However, when i am trying to use the compiled kext i get this error messages in the log:

> May 19 14:10:31 localhost kernel[0]: calling mpo_policy_init for Lilu
> May 19 14:10:31 localhost kernel[0]: Security policy loaded: Lilu Kernel Extension 1.2.3 (Lilu)
> May 19 14:10:31 localhost kernel[0]: kxld[as.vit9696.AppleALC]: The following symbols are unresolved for this kext:
> May 19 14:10:31 localhost kernel[0]: kxld[as.vit9696.AppleALC]: 	__ZN6WIOKit12renameDeviceEP15IORegistryEntryPKcb
> May 19 14:10:31 localhost kernel[0]: Can't load kext as.vit9696.AppleALC - link failed.
> May 19 14:10:31 localhost kernel[0]: Failed to load executable for kext as.vit9696.AppleALC.
> May 19 14:10:31 localhost kernel[0]: Kext as.vit9696.AppleALC failed to load (0xdc008016).
> May 19 14:10:31 localhost kernel[0]: Failed to load kext as.vit9696.AppleALC (error 0xdc008016).
> May 19 14:10:31 localhost kernel[0]: Couldn't alloc class "AppleALC"

How can i solve this renameDeviceIORegistryEntry thing?

Best Regards

**Comment by vit9696** [comment]
Hi,

There currently exists an ABI change between Lilu 1.2.3 and Lilu 1.2.4. While using plugins compiled with Lilu SDK 1.2.3 is fine with both Lilu 1.2.3 and 1.2.4, you will not be able to load plugins compiled against 1.2.4 with Lilu 1.2.3. Please either stick to the release versions of the kexts or use Lilu 1.2.4 compiled from source (preferred).

Vit

**Comment by NextBlaubeere** [comment]
Thank you for your fast response. 👍
