### ISSUE TITLE
Missing PinConfigs for ALC233 - ALC268 in v1.0.6 Release!!!

### ISSUE THREAD

**Issue by vandroiy2013** [vit9696/AppleALC#31]
Just found that in v1.0.6 release files PinConfigs for ALC233 - ALC268 are missing but they defined in release notes.

**Comment by vit9696** [comment]
Great… I must have missed something while compiling the binaries. Sorry.
Not a big deal, they will be present in 1.0.7. I will leave the issue open until 1.0.7 is released.

By the way, what would you recommend to include in 1.0.7?

1. Something messy appeared on [im](http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/page-9#entry2229851), are we interested in fixing/merging this?
1. Some pinconfig [change](https://github.com/arieph7x/AppleALC/commit/3fb3f76bcb8d1ac5f431445381172cd40e8916ce) arised for ASUS. I wonder if it is of any use as well.
1. [ALC892](https://github.com/cecekpawon/AppleALC/tree/master/Resources/ALC892) stuff as well, we tend to be using Mirone at least… and this codec feels tested.
1. Maybe the tools (e. g. Info.plist generator), although I do not think it is a good idea.

**Comment by vandroiy2013** [comment]
1. Many mistakes in this workaround (wrong codec-id, used reserved layout/platform numbers, deleted Mirone resources). You could merge this as another custom resource, but not instead working ones...  
2. Need testing by m-dudarev
3. Why not? Just like ALC1150 with Toleda/Mirone resources
4. You right. It is not a good idea.

**Comment by vit9696** [comment]
1. Might do if I have time
2. Kk
3. Will give it a look later

**Comment by vit9696** [comment]
Well, I am [done](https://github.com/vit9696/AppleALC/commit/878c2083497262938eeb2b406de5daac699f571b) with the two :) Let me know if my changes cause any terrifying issues.

**Comment by vandroiy2013** [comment]
PinConfigs for ALC668 layout 27 and ALC892 layout 5, 7, 9?

**Comment by vit9696** [comment]
Looks like they failed to commit and then merge properly. Hopefully fixed.

**Comment by vandroiy2013** [comment]
Now it's OK except Mirone's layout 9. It's for codecaddress 2 and similar to layout 7. And we found that patches for codecaddress 1 (layout 5, 7) also works fine with codecaddress 2 . So Mirone's layout 9 is useless.

**Comment by vit9696** [comment]
Kicked it out then

**Comment by vit9696** [comment]
Fixed
