### ISSUE TITLE
ALC887VD is not working

### ISSUE THREAD

**Issue by coLATin** [vit9696/AppleALC#36]
my board is GIGABYTE H170TN with ALC887**VD**, use appleALC, system info and volume icon is OK, but no sound, I don't know how to fix this but I think the pathmap and codec file will be helpful, thank you very much.
![pathmap](https://cloud.githubusercontent.com/assets/749762/14586881/61f8ba3e-04d9-11e6-9259-e1656f2e02be.jpg)
[codec_dump.txt](https://github.com/vit9696/AppleALC/files/222631/codec_dump.txt)

**Comment by vandroiy2013** [comment]
Change layout-id.  There is 11 different versions in kext. https://github.com/vit9696/AppleALC/wiki/Supported-codecs

**Comment by coLATin** [comment]
@vandroiy2013 ，of course I did, although 887VD in not in the list u listed, i tried all the layout in dsdt, same result, and some layout make even bad, the speaker icon bacame gray.

**Comment by vandroiy2013** [comment]
ALC887-VD - supported as well. Read changelog https://github.com/vit9696/AppleALC/blob/master/Changelog.md

Do you have any working for you solution? DummyHDA or maybe patched AppleHDA? Post it here i'll see what wrong...

**Comment by coLATin** [comment]
@vandroiy2013 , yes i tried patched AppleHDA, like appleHDA pather(1.2), same result, appleALC is better of course(original appleHDA.kext), so i think mine 887VD nodes is different from common ones, please check the left bottom corner in the picture, only pink and green ports in there.

![170](https://cloud.githubusercontent.com/assets/749762/14587714/4cf5542e-04ea-11e6-9bd4-2fcaf3a7b97f.jpg)

**Comment by vandroiy2013** [comment]
Give me please VoodooHDA dump. I'll see what can be done... Linux dumps are much more complicated for me((((

**Comment by insanelydeepak** [comment]
@coLATin  i will look at your codec_dump and provide appleHDA but if you agreed to use to find better working patch for you

**Comment by coLATin** [comment]
@vandroiy2013 , i tried VOODOOHDA, but can't get dump info for with voodoohdahelper, showed "unknown flag"....

**Comment by coLATin** [comment]
@insanelydeepak , that's will be great, i tried appleHDA first, but no sound, 95% because of the pinconfig and node difference, thanks a lot :+1:

**Comment by insanelydeepak** [comment]
@coLATin plz provide DSDT , Clover Config.plist send it to insanelydeepak@gmail.com

**Comment by cecekpawon** [comment]
Uhm completely forgot how to pinconfig since i wrote [this](https://github.com/cecekpawon/OSXOLVED/blob/master/yod-VerbsInColor.php), but the purposes is to made some Linux dump more readable with table, color & value in HTML reports.

`yod-VerbsInColor.php <linux codecdump>`
