### ISSUE TITLE
Patch bug

### ISSUE THREAD

**Issue by 935713827** [vit9696/AppleALC#38]
I try to join other 'Patch'
If other ‘Patch ’exists,  then he will cause 'AppleLPC' or 'AppleHDA'Patch fail
Only restart
Maybe two will succeed
Two  different binary files Patch

Such as' AppleHDA 'or' AppleLPC '
The binary name here is just a comparison.

**Comment by vit9696** [comment]
I am unable to understand incomprehensible mind stream.

**Comment by 935713827** [comment]
……well
