### ISSUE TITLE
Controllers.plist could add support for HD4000 ig-platform-id 0x0166004?

### ISSUE THREAD

**Issue by itribal** [vit9696/AppleALC#39]
At first, I want to do it myself, but i don't know what means about  `<key>Platform</key>
		<integer>23461891</integer>`, like this:
`<dict>
		<key>Device</key>
		<integer>358</integer>
		<key>Model</key>
		<string>Laptop</string>
		<key>Name</key>
		<string>Intel HD4000 HDMI (ig-platform-id 0x01660003)</string>
		<key>Patches</key>
		<array>
			<dict>
				<key>Count</key>
				<integer>1</integer>
				<key>Find</key>
				<data>
				AgUAAAAEAAAHBAAAAwQAAAAEAACBAAAABAYAAAAEAACB
				AAAA
				</data>
				<key>MinKernel</key>
				<string>13</string>
				<key>Name</key>
				<string>AppleIntelFramebufferCapri</string>
				<key>Replace</key>
				<data>
				AgUAAAAIAAAHBAAAAwQAAAAIAACBAAAABAYAAAAIAACB
				AAAA
				</data>
			</dict>
		</array>
		<key>Platform</key>
		<integer>23461891</integer>
		<key>Vendor</key>
		<string>Intel</string>
	</dict>`

And I don't find a way to choice the number for my laptop. the following line was used in my Clover config.plist for patch  AppleIntelFramebufferCapri

`<dict>
				<key>Comment</key>
				<string>HDMI-video, 64MB BIOS, HD4000 0x01660004 #1 of 2</string>
				<key>Disabled</key>
				<false/>
				<key>Name</key>
				<string>AppleIntelFramebufferCapri</string>
				<key>Find</key>
				<data>BABmAQEDAQEAAAAC</data>
				<key>Replace</key>
				<data>BABmAQECBAIAAAAE</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>HDMI-video, 64MB BIOS, HD4000 0x01660004 #2 of 2</string>
				<key>Disabled</key>
				<false/>
				<key>Name</key>
				<string>AppleIntelFramebufferCapri</string>
				<key>Find</key>
				<data>MAIAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAABAAAAQAAAAAAAAAAAAAAA</data>
				<key>Replace</key>
				<data>MAIAAAIFAAAABAAABwQAAAMEAAAABAAAgQAAAAQGAAAABAAAgQAAAAAAAAAAAgAR</data>
			</dict>`

Could add it to Controllers.plist?
Thanks for your time.

**Comment by 935713827** [comment]
Can

**Comment by itribal** [comment]
Thx very much. Please add it.

**Comment by itribal** [comment]
Thx, but how to add it?

**Comment by vit9696** [comment]
I am not certain about HDMI stuff, but we do not add connector patches, only patch the hdmi stream.
if I remember correctly, (cc @vandroiy2013, I am not sure about this), HD4000 requires connector patches anyway, so adding an incomplete patch here is unreasonable.  

Considering the namings:
- Platform stands for AAPL,ig-platform-id; 
- Device stands for device-id;
- Vendor stands for vendor-id to match your GPU.
