### ISSUE TITLE
Suggestion for AppleALC

### ISSUE THREAD

**Issue by huangwei0418** [vit9696/AppleALC#40]
AppleALC is a very exciting project，I want to thank you for your hard work consider donating；

  For  the codec database，I hope it can  keep updated weekly, so AppleAlC can support more kinds of sound card  better and better.

toleda, Mirone, bbc9,RehabMan，insanelydeepak，autumnrain, slice2009 ,anonymousnbs, vusun123 ,you can invite the following people to help you maintaining codec database, the more people help, the kext will be more perfect,thank you for your hard work again! 

toleda,Mirone: AppleHDA
bbc9: AppleHDA
insanelydeepak:AppleHDA 
autumnrain, slice2009: voodoohda
anonymousnbs, vusun123 :Hackintosh Vietnam Tool

Add Spport for:
Cirrus LogicCS4213 Laptop
IDT_92HD90BXX 76e7 Laptop
IDT_92HD73C1 Laptop
IDT_92HD66C3-65 Laptop
Realtek ALC292 Laptop
Realtek ALC665 Laptop
More Models can be found here:
https://sourceforge.net/p/voodoohda/code/HEAD/tree/tranc/Models.h

**Comment by vit9696** [comment]
@huangwei0418, thanks for your warm words.

AppleALC database is built thanks to contributors, not to myself. @vandroiy2013 is kind enough to add & convert various codecs from the net but he definitely cannot do everything.

It's relatively nice to have a checklist you wrote, but I guess it'd be better if people with such hardware came and created the corresponding pull-requests confirming that these changes work for them. Fortunately an excessive wiki is covering all the caveats.

Vit

**Comment by huangwei0418** [comment]
Writing a small command line tool should be considered, which can encourage users to upload kext log when applealc has been loaded and working correctly. Further designing an app is better, not only for playing a short test music, but also can provide a key feedback button, if the test result is OK, when the user clicks a button feedback button Applealc logs, Info.plist, PlatformsXX.xml.zlib, layoutXX.xml.zlib wiil be uploaded one-click; otherwise, the log will be uploaded only Applealc kext log.

**Comment by vit9696** [comment]
@huangwei0418, eh, not that I do not see the point for this but it is out of my own interest. I. e. I find no value in simplifying things for newbies, so that they remain having very little knowledge about how things work.
For this reason I would rather encourage people read more and understand better than click a simple button and be happy. If you feel that you can write something alike and are willing to help I won't stop you though.

**Comment by vandroiy2013** [comment]
I don't think it's a good idea... App, feedback button...
