### ISSUE TITLE
how to add pinconfigdata and pathmap? alc887VD

### ISSUE THREAD

**Issue by coLATin** [vit9696/AppleALC#43]
alc887VD, gigabyte thin ITX, with LVDS ports, so much different with common alc887VD, I get pin confugdata and pathmap , how to add the code to applealc?
 pinconfigdata: 
01a71c10 01a71d40 01a71e01 01a71f01
01871c20 01871d90 01871ea1 01871f01
01471c30 01471d01 01471e17 01471f29 01470c02

pathmap: 
20( [Fixed] Speaker at Int N/A)[
		20( [Fixed] Speaker at Int N/A)
		12(Audio Mixer)
		2(Audio Output)
]
24( [Jack] Mic at Ext Rear)[
		9(Audio Input)
		34(Audio Mixer)
		24( [Jack] Mic at Ext Rear)
]
26( [Jack] Line Out at Ext Rear)[
		26( [Jack] Line Out at Ext Rear)
		13(Audio Mixer)
		3(Audio Output)
]

**Comment by vandroiy2013** [comment]
You have to make your own platforms.xml.zlib & layout.xml.zlib with your pathmap. Then add it into ALC887 folder with free custom layout-id and with changes to ALC887/info.plist using Xcode. Add pinconfig into pinconfigs.kext->info.plist. Build kext and try it. If it's OK - make pull request with your changes.
