### ISSUE TITLE
1-channel only

### ISSUE THREAD

**Issue by MaximKiselev** [vit9696/AppleALC#44]
System: El capitan 10.11.4
Codec: ALC 892
Board with 3 audio port (red, blue, green)
Layout: checked all(1,2,3,5,7), only one channel is active. Sound is enable but works only left channel.
PS kext before was not patched.

**Comment by vandroiy2013** [comment]
ALC 892 is working perfect (2 and more channels). Tested many times on applelife.ru. Search problem in your hardware.

**Comment by MaximKiselev** [comment]
Hm, ok. Before I use [this patch](https://github.com/toleda/audio_CloverALC) . It is works. All channels

**Comment by vandroiy2013** [comment]
All Toleda workaronds for your ALC 892 merged in AppleALC under layout 1, 2 and 3. No changes at all.

**Comment by MaximKiselev** [comment]
@vandroiy2013 , thanks a lot. Go to search reason :(

**Comment by vit9696** [comment]
@MaximKiselev, I suggest you to compare the resources honestly (including the pinconfigs). Maybe Toleda changed something after or before the merging? Let us know if you find something :)

**Comment by vandroiy2013** [comment]
Toleda's repo for ALC892 changed almost 2 years ago... So it's not that case))))

**Comment by MaximKiselev** [comment]
All fine. I'm close issue. Thx all.
