### ISSUE TITLE
Creative CA0132

### ISSUE THREAD

**Issue by nmano** [vit9696/AppleALC#47]
Hi Vit9696
Thanks for great job.sound worked good.but Volume Bar is fake.
Not working sound bar for Creative CA0132
i am waiting for your update.
#Yassinex AppleALC.kext is sound bar worked.
http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/page-24#entry2239226

Thank Lots.

**Comment by vit9696** [comment]
I unfortunately have no time to get deeply involved in this issue.   
If you have a working kext, extract its resources and make a pull-request. It will be discussed and merged in one or or the other form.

**Comment by nmano** [comment]
I have working kext AppleHDA and AppleALC
I try and rebuild no susses.same sound worked but Volume bar not work.

**Comment by vit9696** [comment]
Well, it is obviously not possible to have a working solution that stops working after a rebuild when you do exactly the same steps. Look for a typo somewhere, I know it is hard to believe there is one but you must be laughing at yourself once you find it. Good luck!

**Comment by nmano** [comment]
I understand .I conform AppleALC CA0132 not work sound Bar.
I need help.
You are a master like netkas or rehapman.
Where are you before
i give you challenge and pay $50
I have x99gaming g1wifi
Its worked with fake CPU ID with clover.
I need a kext for fake cpu ID.
I know you can do please build a kext for fake cpu ID.
X99 board 10.11 worked with fake ID I found this for x99 with out fake ID AppleIntelCPUPowerManagement.kext not work.
 0x0306E0
http://www.tonymacx86.com/threads/good-news-for-x99-10-11-haswell-e-el-capitan.178425/

please look this.
thank you.

**Comment by vit9696** [comment]
XD you made a mistake in suggesting me money.  
Learn yourself.
