### ISSUE TITLE
CA0132

### ISSUE THREAD

**Issue by nmano** [vit9696/AppleALC#48]
Finally CA0132 worked Everything  to Rebuild.
Mainly volume adjuster worked now.
I upload  files to Resources.
Please update Resources
Layout ID-0-12
Thank you for AppleALC Team.
Thank you, guys
[Debug.zip](https://github.com/vit9696/AppleALC/files/288876/Debug.zip)
[Layout 0-12.zip](https://github.com/vit9696/AppleALC/files/288877/Layout.0-12.zip)

**Comment by vandroiy2013** [comment]
Hello. I dont't understand the mess you attached... I need platforms.xml.zlib, layout.xml.zlib, binpatches and one pinconfig. 1 not 12...

**Comment by nmano** [comment]
I am sorry I upload wrong file before.
I re upload platforms.xml.zlib, layout.xml.zlib and pinconfig. Layout =0
[CA0132.zip](https://github.com/vit9696/AppleALC/files/298492/CA0132.zip)

**Comment by nmano** [comment]
binpatchs For CA0132
[Info.plist.zip](https://github.com/vit9696/AppleALC/files/298501/Info.plist.zip)

**Comment by nmano** [comment]
X99 HDEF controller
Find A08C
Replace 
[Controllers.plist.zip](https://github.com/vit9696/AppleALC/files/298519/Controllers.plist.zip)
208D

**Comment by vit9696** [comment]
CA0132 fixes are now present in trunk
