### ISSUE TITLE
CX20590 zlib Error ‘Lenovo G470’

### ISSUE THREAD

**Issue by 935713827** [vit9696/AppleALC#49]
CX20590 zlib  error causing node error can not drive the sound card
Available file 'AppleHDA Patch' generate

Lenovo G470

[Uploading zlib.zip…]()

**Comment by vandroiy2013** [comment]
What????

**Comment by 935713827** [comment]
CX20590  Platforms.xml.zlib Error

**Comment by 935713827** [comment]
I suggest used 'AppleHDA Patch‘  zlib flie

**Comment by 935713827** [comment]
I only feedback

**Comment by vandroiy2013** [comment]
Where? There are two platforms.xml.zlib in project... What are you talking about? Layout-id 3 and 12 confirmed working on several laptops... It is a useless feedback without dumps and reports... What is it "AppleHDA Patch"? Can you be more specific?

**Comment by 935713827** [comment]
AppleALC-master/Resources/CX20590/PlatformsM.xml.zlib
 ‘Lenovo G470’ 
unable to work normally
 ‘AppleHDA Patch’ generated zlib file could use

**Comment by 935713827** [comment]
http://www.insanelymac.com/forum/files/file/496-applehda-patcher/

**Comment by vandroiy2013** [comment]
This platforms are SIMILAR to each other!
![2016-06-02 17 59 11](https://cloud.githubusercontent.com/assets/8144780/15749782/4d942d44-28ec-11e6-827b-0d1696b69a05.png)
![2016-06-02 18 00 04](https://cloud.githubusercontent.com/assets/8144780/15749787/50db7322-28ec-11e6-86db-170f9140166b.png)
The ONE AND ONLY change is that in AppleALC unused (for hackintoshers) CommonPeripherialDSP was removed to reduce kext size...
![2016-06-02 18 00 33](https://cloud.githubusercontent.com/assets/8144780/15749866/bb2874f0-28ec-11e6-87f4-d66eb81cd028.png)
![2016-06-02 18 02 16](https://cloud.githubusercontent.com/assets/8144780/15749897/e249dfd8-28ec-11e6-83b7-f0b937120fe6.png)
Search the problem in your rig. CX20590 confirmed working 100% on both layout-id's.

**Comment by vandroiy2013** [comment]
[https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/#post-577230](url)
Verified codec list (100% working) English/Russian

**Comment by 935713827** [comment]
Ok  thank you very much
