### ISSUE TITLE
newest 10.11.6 beta 2 applealc doesnt work 

### ISSUE THREAD

**Issue by Gamedev1909** [vit9696/AppleALC#50]
[AppleHDA.kext.zip](https://github.com/vit9696/AppleALC/files/302388/AppleHDA.kext.zip)
here is the newest appleHDA

**Comment by vandroiy2013** [comment]
Everything is working OK on 10.11.6 Dev Beta 2. At least on 10 different rigs with different codecs...

**Comment by Gamedev1909** [comment]
well it's not working here in my laptop desktop tablet or other 8 desktops

**Comment by vandroiy2013** [comment]
I want to believe but without logs and reports i can't... 10 different testers reported yesterday that everything is working OK including myself with 2 rigs. ALC888, ALC887, ALC892 etc.

**Comment by Gamedev1909** [comment]
no 1150? reported well i just did and getting logs is a bit hard as HWsensors3 broke my clover install while i was trying to fix the issue

**Comment by vandroiy2013** [comment]
It is not the problem in AppleALC. Definitely the problem in your system. Try to install clean AppleHDA, check audio patches in config.plist, check dummy kexts/fakeSMC.kext for old pinconfig... There were no changes for audio in 10.11.6 Dev Beta 2 so it should work as well as on 10.11.5. And it is working. Confirmed...

**Comment by vit9696** [comment]
@Gamedev1909 thanks for reporting but @vandroiy2013 is correct.
It is uneasy to check AppleALC status without viewing the logs, especially given that AppleHDA was unchanged.

@vandroiy2013 may we merge #48 by the way? It looks almost clean to me.

**Comment by vandroiy2013** [comment]
@vit9696 Let's wait Wern Apfel from insanelymac. He is trying to make 1 universal layout for CA0132...

**Comment by vit9696** [comment]
Ah, alright, that sounds like a good idea. As for this issue I am closing it until the logs appear.
