### ISSUE TITLE
Codec: SigmaTel STAC9228

### ISSUE THREAD

**Issue by nmano** [vit9696/AppleALC#51]
Dell XPS M1730
Codec: SigmaTel STAC9228
Address: 0
AFG Function Id: 0x1 (unsol 1)
Vendor Id: 0x83847616
Subsystem Id: 0x102801f7
Revision Id: 0x100201
I add some file.
Thank you.
[SigmaTel STAC9228.zip](https://github.com/vit9696/AppleALC/files/303633/SigmaTel.STAC9228.zip)

**Comment by vit9696** [comment]
Um, could you please make layouts/platforms based on the dump? Otherwise adding the support of this codec will likely take time.

Also, regarding this https://github.com/vit9696/AppleALC/issues/50#issuecomment-224268478, I hope insanely crash was not the cause of a loss of this information, and it is being readied.

**Comment by nmano** [comment]
layout3.xml.zlib and Platforms.xml.zlib
[Archive.zip](https://github.com/vit9696/AppleALC/files/306771/Archive.zip)
can you check this files

**Comment by vandroiy2013** [comment]
Hello @nmano . You forgot pinconfig data. Can't add it without it...

**Comment by nmano** [comment]
Please look this files.
[codecgraph.zip](https://github.com/vit9696/AppleALC/files/308901/codecgraph.zip)

**Comment by nmano** [comment]
[Info.plist.zip](https://github.com/vit9696/AppleALC/files/308910/Info.plist.zip)

**Comment by vandroiy2013** [comment]
Why do you think i should dig in this mess? If you need this codec support in AppleALC please provide CORRECT data for it... PinConfig, working layout/platforms, binpatches, device-id, vendor-id etc.

**Comment by nmano** [comment]
I try applehda its not work.
Only worked voodaHDA.
I don’t know why 
I need to try AppleALC.kext

**Comment by vit9696** [comment]
AppleALC is not different from what you call "AppleHDA". It is just a convenient method to patch AppleHDA not a new technique to alter it.  
If you do not know what you want, your question is not for github but for the support forum, praying someone decides to help you.
