### ISSUE TITLE
ALC1150 on GA-Z170-Gaming-K3 motherboard

### ISSUE THREAD

**Issue by arsradu** [vit9696/AppleALC#57]
Hi there,

I couldn't get my work PC to work in terms of sound, using the latest version of AppleALC kext, in El Capitan. AppleHDA kext is native, and I cleared my config.plist. Also, I used Layout_id=1. Still..no sound.

Could you please, advise?

**Comment by vit9696** [comment]
Hi,
It is not possible for me to help you right now, but I can check that everything goes by design if I look at the log. Please install a debug kext, add -alcdbg to boot arguments, and run 
`cat /var/log/system.log | grep AppleALC`
Copy the results here within a spoiler tag or something.

**Comment by arsradu** [comment]
Hi vit. :)

Will do. I just can't get my hands on a debug version of this kext.

Can you help?

**Comment by vit9696** [comment]
Xcode has file list panel on the left. Compiled binaries display in the Products section, right click on the kext and choose Show in Finder. There also are precompiled binaries on the release page.

**Comment by arsradu** [comment]
Ok, will try that, as well.

It's weird cause I do have Layout Id set to 1 in Clover.
![screen shot 2016-06-17 at 3 53 40 pm](https://cloud.githubusercontent.com/assets/5080446/16151116/dbe0f8e4-34a3-11e6-8acb-0b735fb3d456.png)

**Comment by arsradu** [comment]
As I suspected, it's a problem with the layout ID.

Here's the log, from the debug build:

mac:~ radu$ cat /var/log/system.log | grep AppleALC
Jun 17 00:23:11 localhost kernel[0]: calling mpo_policy_init for AppleALC
Jun 17 00:23:11 localhost kernel[0]: Security policy loaded: AppleALC Kernel Extension (AppleALC)
Jun 17 00:23:13 bucmac0053 kernel[0]: AppleALC: alc @ layout-id was not provided by controller at HDEF
Jun 17 11:57:10 localhost kernel[0]: calling mpo_policy_init for AppleALC
Jun 17 11:57:10 localhost kernel[0]: Security policy loaded: AppleALC Kernel Extension (AppleALC)
Jun 17 11:57:12 bucmac0053 kernel[0]: AppleALC: alc @ layout-id was not provided by controller at HDEF
Jun 17 13:05:41 localhost kernel[0]: calling mpo_policy_init for AppleALC
Jun 17 13:05:41 localhost kernel[0]: Security policy loaded: AppleALC Kernel Extension (AppleALC)
Jun 17 13:05:42 localhost kernel[0]: AppleALC: alc @ layout-id was not provided by controller at HDEF
Jun 17 13:40:44 localhost kernel[0]: calling mpo_policy_init for AppleALC
Jun 17 13:40:44 localhost kernel[0]: Security policy loaded: AppleALC Kernel Extension (AppleALC)
Jun 17 13:40:44 localhost kernel[0]: AppleALC: alc @ layout-id was not provided by controller at HDEF
Jun 17 16:04:58 localhost kernel[0]: calling mpo_policy_init for AppleALC
Jun 17 16:04:58 localhost kernel[0]: Security policy loaded: AppleALC Kernel Extension (AppleALC)
Jun 17 16:04:59 localhost kernel[0]: AppleALC: alc @ layout-id was not provided by controller at HDEF
Jun 17 16:22:31 localhost kernel[0]: calling mpo_policy_init for AppleALC
Jun 17 16:22:31 localhost kernel[0]: Security policy loaded: AppleALC Kernel Extension (AppleALC)
Jun 17 16:22:31 localhost kernel[0]: AppleALC: alc @ layout-id was not provided by controller at HDEF
Mac:~ radu$

**Comment by vit9696** [comment]
Do not use clover configurator, edit Info.plist manually. This looks like not an AppleALC bug.

**Comment by arsradu** [comment]
Info.plist? You mean config.plist, right?

I did use Clover Configurator to edit it. But it's still ok, even if I edit it manually.
![screen shot 2016-06-17 at 5 33 14 pm](https://cloud.githubusercontent.com/assets/5080446/16154036/b714075a-34b1-11e6-96fa-b5b2ba27d278.png)

What about the info.plist zip file I sent earlier? Does that help in any way?

**Comment by vit9696** [comment]
What about FixHDA (or HDEF) in ACPI patches do not remember the exact name?

**Comment by arsradu** [comment]
It's FixHDA, Vit. But it's not checked.
The only patch I applied in that section is Rename HDAS to HDEF. Is it necessary for your kext?

**Comment by vit9696** [comment]
I think it is. I generally edit SSDT myself, so I am not sure what changes are ncessary for Clover. Read its manual ;)

**Comment by arsradu** [comment]
Well...if the target of the kext is HDEF (which I suppose it is), then the rename is ok, since now I do have HDEF in ioreg (I had HDAS before).

I need to find a way to change my layout-id from 00 00 00 00 to 01 00 00 00 (if I'm not mistaken).
Any idea?

**Comment by vit9696** [comment]
0 layout-id is missing layout-id, i.e. likely missing _DSM. You must fix your DSDT either with FixHDA or with SSDT edits. OEM DSDT does not contain _DSM methods in HDEF even if renamed.

**Comment by arsradu** [comment]
Wit FixHDA I get a KP. I extracted the DSDT and...maybe I don't know where to look (most likely) but I seem to have _DSM. I wish Clover would work with this as it used to work with my previous build. :(
Can you help to get this fixed? I have no clue what where to go from here.

**Comment by vandroiy2013** [comment]
Try to use arbitrary device injection in clover. Read clover manual.
http://www.insanelymac.com/forum/topic/282787-clover-v2-instructions/?p=2163533

**Comment by arsradu** [comment]
Hi, Vandroiy

I was looking into that this morning, but...in my boot.log, I don't have any Realtek device (I looked for 10EC and Realtek) so...I'm not sure where to start with this method. But interestingly enough, I can see the device in DPCI Manager. 

![post-1303722-0-23712700-1466226110_thumb](https://cloud.githubusercontent.com/assets/5080446/16170314/8b80084a-3557-11e6-923c-6482b846b6a0.png)

**Comment by vandroiy2013** [comment]
Use bdmesg in terminal to get clover bootlog for PCI address information. 
Also you should look Audio Device but NOT CodecID
![d38f307a-3557-11e6-9b67-f457590ba04b](https://cloud.githubusercontent.com/assets/8144780/16170375/392c10fa-3559-11e6-9aa9-2635031f4d21.png)

**Comment by arsradu** [comment]
Ha! Found it! :D 

`0:100  0:000  PCI (00|00:1F.03) : 8086 A170 class=040100`

**Comment by vandroiy2013** [comment]
I suggest you to move to the clover topic. This place is for discussing AppleALC issues. 
Closed...
