### ISSUE TITLE
ALC292 codec support --LayoutID set error

### ISSUE THREAD

**Issue by huangwei0418** [vit9696/AppleALC#58]
There is a error in ALC292 codec support ,the error  is layoutID in file AppleALC / Resources / ALC292 / Layout12.xml.zlib

**Comment by vandroiy2013** [comment]
Sorry. But i don't understand where is this error. What do you mean?

**Comment by huangwei0418** [comment]
![1](https://cloud.githubusercontent.com/assets/18703675/16167078/b4ea909e-3523-11e6-9605-02de3f32f91c.png)

In file AppleALC / Resources / ALC292 / layout12.xml.zlib, the number LayoutID should be 12 instead of 1.

**Comment by vandroiy2013** [comment]
Layout-id in layout.xml.zlib doesn't matters. AppleALC don't use this data at all. Resource Converter does his job very well)))

I also know about unused pathmaps)))) It is not errors - it is unfinished optimizations)))) Thanks.
