### ISSUE TITLE
Issue in layout4.xml.zlib for Realtek ALC3236

### ISSUE THREAD

**Issue by nguyenlc1993** [vit9696/AppleALC#62]
Hi @vit9696,

My laptop is ASUS K501LX (i7 5500U, HD5500) with audio codec of Realtek ALC3236 (a custom version of ALC233).

I used your kext with layout-id = 4 and got speaker and headphone worked, but internal mic didn't work. After checking /Resources/ALC233/layout4.xml.zlib, I found that MuteGPIO for Mic should be set to 1,342,242,843 (0x500100**1B**). So I built a custom version of AppleALC with modified layout4.xml.zlib and got internal mic worked.

Hope this solution will be included in later commit. Btw, your kext is awesome, it worked great on my first try. 😄

**Comment by vit9696** [comment]
Hi, thanks for noting. @vandroiy2013 may we just update 4 or that needs to be a separate layout?

**Comment by vandroiy2013** [comment]
@vit9696, @nguyenlc1993  I will update it tomorrow. Thanks.

**Comment by vandroiy2013** [comment]
Done. Issue closed. @nguyenlc1993 Thanks for finding bug...
