### ISSUE TITLE
Missing credits in Controllers.plist

### ISSUE THREAD

**Issue by Piker-Alpha** [vit9696/AppleALC#64]
If it wasn't for me and my work, then we would still not have HDMI audio (since 10.8) so I think that I deserve the credits for it. Thanks.

**Comment by vandroiy2013** [comment]
Hello. There is no "credits" in *.plists. This is just human readable data for maintaining database. All credits are in readme.md on main page. You also mentioned in it.

**Comment by vit9696** [comment]
I've just added a better note to readme, thanks)

**Comment by Piker-Alpha** [comment]
The add it. Like you [did here](https://github.com/vit9696/AppleALC/blob/master/Resources/ALC892/Info.plist#L5)
