### ISSUE TITLE
ALC269 Internal Mic doesn't working

### ISSUE THREAD

**Issue by BananaJoe66** [vit9696/AppleALC#65]
Hi! 
I have ALC269 and i use layout 3. Everything is working very good (hdmi audio, external/internal speaker) but internal mic doesn't work. The system detect but doesn't recognise noise.

**Comment by vandroiy2013** [comment]
Try another layout-id.

**Comment by BananaJoe66** [comment]
I tried all layout and 28 was work but HDMI audio wasnt work.

**Comment by al6042** [comment]
Try layout ID 29... this works on my Lenovo T530 and with a friends E430

**Comment by vit9696** [comment]
I guess this is not a place to ask for fixed resources, and the issue is pretty dated as well. Please reopen it when you obtain working resources to include in AppleALC. Thanks.
