### ISSUE TITLE
ALC1150 microphone sound small

### ISSUE THREAD

**Issue by Meow1688** [vit9696/AppleALC#67]
Hello On my microphone sound small, whether it is the front or rear are the same

motherboard：GIGABYTE G1.Sniper B6
Audio：ALC1150

**Comment by vit9696** [comment]
What layout are you using? I actually was thinking of boosting the microphone for myself (layout 1).

**Comment by Meow1688** [comment]
I'm layout 1 too，ls it have progress now?
在 2016年7月22日，15:40，vit9696 <notifications@github.com<mailto:notifications@github.com>> 写道：


What layout are you using? I actually was thinking of boosting the microphone for myself (layout 1).

**Comment by vit9696** [comment]
No, because I'd rather try different layouts first. E.g. Mirone's 5. Could you tell me if 5th layout has any issues including the microphone thing? I can see <key>Boost</key><integer>1</integer> there, which means it has +10 dB by default.

**Comment by Meow1688** [comment]
I tried Layout 1 and 7, in addition to a small microphone sound other than the normal.

iPhoneから送信

2016/07/22 16:32、vit9696 <notifications@github.com<mailto:notifications@github.com>> のメッセ`ジ:


No, because I'd rather try different layouts first. E.g. Mirone's 5. Could you tell me if 5th layout has any issues including the microphone thing? I can see Boost1 there, which means it has +10 dB by default.

―

**Comment by vit9696** [comment]
Well, if maxing the level in Preferences does not solve the issue (it does for me), I guess you could unpack PlatformsM.xml.zlib with zlip.pl (see Tools folder):
`zlib.pl inflate PlatformsM.xml.zlib > PlatformsM.xml`
and increase Boost on 24th and 25th nodes by finding
`<key>Boost</key>`
`<integer>1</integer>`
and replacing 1 with 2 or 3.
To pack it back use:
`zlib.pl deflate PlatformsM.xml > PlatformsM.xml.zlib`
Recompile kext afterwards and try layout 5 or 7.

**Comment by Meow1688** [comment]
In preference which has the microphone at maximum volume is still the same , well thank you , I will try the method you said .

iPhoneから送信

2016/07/22 17:32、vit9696 <notifications@github.com<mailto:notifications@github.com>> のメッセ`ジ:


Well, if maxing the level in Preferences does not solve the issue (it does for me), I guess you could unpack PlatformsM.xml.zlib with zlip.pl (see Tools folder):
zlib.pl inflate PlatformsM.xml.zlib > PlatformsM.xml
and increase Boost on 24th and 25th nodes by finding
<key>Boost</key>
<integer>1</integer>
and replacing 1 with 2 or 3.
To pack it back use:
zlib.pl deflate PlatformsM.xml > PlatformsM.xml.zlib
Recompile kext afterwards and try layout 5 or 7.

―

**Comment by Meow1688** [comment]
thank you very much for your help.  Microphone volume already has improved. Pre-volume or too small, do not know where there is need to amend,Now use Boost 3, layout 7.
在 2016年7月22日，17:32，vit9696 <notifications@github.com<mailto:notifications@github.com>> 写道：


Well, if maxing the level in Preferences does not solve the issue (it does for me), I guess you could unpack PlatformsM.xml.zlib with zlip.pl (see Tools folder):
zlib.pl inflate PlatformsM.xml.zlib > PlatformsM.xml
and increase Boost on 24th and 25th nodes by finding
<key>Boost</key>
<integer>1</integer>
and replacing 1 with 2 or 3.
To pack it back use:
zlib.pl deflate PlatformsM.xml > PlatformsM.xml.zlib
Recompile kext afterwards and try layout 5 or 7.

**Comment by vit9696** [comment]
I committed mic-boosted microphone layout 11 for 1150. It can be used now out of the box.

**Comment by dobryc** [comment]
Hello, @vit9696 ! 
I have the same problem with mic input gain, but i really need help with boosting it's volume.
I have ALC 887 and use layout 11, that's best for my setup.
I've downloaded AppleALC sources, went to Resources/ALC887.
![2017-02-12 1 07 00](https://cloud.githubusercontent.com/assets/11852501/22857876/9fabd352-f0bf-11e6-9482-d9e5389f5b15.png)
What file should i edit? @Meow1688  edited this file: PlatformsM.xml.zlib. Will it be the same in my case? And the most difficult for me to understand, how to figure out Node id i should edit "Boost" key?
I want my "Internal speaker" (green back output) volume boost too.

Many thanks in advance! Sorry for opening old issue, have a nice day!

**Comment by vit9696** [comment]
Hi, layout-id 11 is using PlatformsID.xml.zlib, check codec Info.plist for similar lines next time:
```
				<key>Id</key>
				<integer>11</integer>
				<key>Path</key>
				<string>PlatformsID.xml.zlib</string>
```
You could find node id via parsing pinconfiguration via e.g. PinConfigurator.app. But these details are better to check on insanelymac or somewhere alike, as they are unrelated to AppleALC.

**Comment by dobryc** [comment]
@vit9696 Thank you for quick reply, i got it! 
Should i post my results if i'll be lucky? 
I have MSI H81-p33.

**Comment by vit9696** [comment]
Well… if you would like a boosted layout to be provided by AppleALC I actually could imagine this.

**Comment by dobryc** [comment]
@vit9696 Morning! I feel so stupid about building kext. I figured out that i need boost at 24th and 25th pin nodes, but when i unpacked PlatformsID.xml.zlib, then edited (opened .xml with text editor and changed <boost> from 1 to 3, dec), then packed it again (with zLib tool), then builded it in Xcode (one more thing i fell stupid is where released .kext stored).
Anyway, i gave this idea up till this morning and my hack hasnt booted because of appleALC (does Xcode build appleALC right to clover kexts folder?!?!). Replaced it with vanilla one and booted successfully. 
Could you point me, where i was wrong?

**Comment by vit9696** [comment]
Morning, first of all I have to say that Xcode building process has nothing to do with the clover folder. The built kexts are stored in DerivedData either in ~/Library/.../ folder or in project root.

If it failed to boot for (was it a panic? a hang?) it might have been the same AppleALC (although there is no way to prove now), just one more rarely happening bug. Next time it is best to compare… 

What you did is absolutely right (from what you describe at least), perhaps it was just a mere typo somewhere.

**Comment by dobryc** [comment]
@vit9696 Finally, i compiled kext and got my mic boost. 
[PlatformsID.xml.zlib.zip](https://github.com/vit9696/AppleALC/files/769232/PlatformsID.xml.zlib.zip)
I changed 11th's layout path in here.
Many thanks for AppleALC and help!

**Comment by vit9696** [comment]
Could you make it a separate layout so that we could merge it into AppleALC?

**Comment by dobryc** [comment]
Will try to do this tonight.
