### ISSUE TITLE
No audio interfaces Cirrus Audio CS4210

### ISSUE THREAD

**Issue by Sexytaco** [vit9696/AppleALC#71]
Hi,

Support for my audio codec was added by InsanelyDeepak, who was kind enough to patch AppleHDA.kext for me. He committed the update to AppleALC with support for it. Big thanks!

Unfortunately, the latest version of AppleALC doesn't work at all for me. There aren't any sound outputs or inputs. The patched AppleHDA worked great, save for the external mic. I reverted to vanilla HDA, repaired permissions with Kext Wizard, copied AppleALC to /EFI/EFI/CLOVER/kexts/10.11, and rebooted. 

Any ideas?

Thanks

EDIT: I'm injecting layout id 13 in Clover.

**Comment by vit9696** [comment]
Cirrus Logic CS4210 is there at layout-id 13. Try contacting InsanelyDeepak, maybe he has an idea what's wrong.

**Comment by sexytaco** [comment]
@vit9696 I'm injecting layou-id 13 with Clover. InsanelyDeepak suggested it was an issue with AppleALC.

**Comment by vit9696** [comment]
I personally doubt it. Try the debug version with -alcdbg argument. And paste 
cat /var/log/system.log | grep AppleALC
somewhere.

**Comment by sexytaco** [comment]
@vit9696 

$ cat /var/log/system.log | grep AppleALC
Aug  3 19:03:42 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:42 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.kext.triggers
Aug  3 19:03:42 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:42 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.filesystems.autofs
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AppleUSBAudio
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.X86PlatformShim
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AGPM
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.ApplePlatformEnabler
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ resource-request arrived layout
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ checking codec 1013:4210:100101
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ selecting from 1u files
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ comparing 0u layout D/D
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) Found layout at 0u index
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ resource-request arrived layout
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ checking codec 1013:4210:100101
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ selecting from 1u files
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ comparing 0u layout D/D
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) Found layout at 0u index
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ resource-request arrived paltform
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ checking codec 1013:4210:100101
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ selecting from 1u files
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ comparing 0u layout D/D
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) Found platform at 0u index
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ resource-request arrived paltform
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ checking codec 1013:4210:100101
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ selecting from 1u files
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) alc @ comparing 0u layout D/D
Aug  3 19:03:43 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) Found platform at 0u index
Aug  3 19:03:44 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:44 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.filesystems.ntfs
Aug  3 19:03:44 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:44 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AudioAUUC
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.IOBluetoothHIDDriver
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AppleHSBluetoothDriver
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AppleHIDTransport
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AppleMultitouchDriver
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:45 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.driver.AppleTopCaseHIDEventDriver
Aug  3 19:03:58 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ invoked at kext loading/unloading
Aug  3 19:03:58 Swagbook-Pro kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.filesystems.smbfs

**Comment by vit9696** [comment]
I checked the log, and can confirm that AppleALC submits 13th layout and platform to AppleHDA. Byte patching part is not present here for some reason though (do you have something spamming to the log or did you wait quite some time to get it?), so I cannot tell you that it was done correctly. However, given that layouts and platforms are routed, patch session was performed without any problems.

I suggest you or InsanelyDeepak compare the resources and patches present in AppleALC to the ones that are ok to you (https://github.com/vit9696/AppleALC/tree/master/Resources/CS4210). Perhaps there was some misunderstanding and different/not recent data was committed.

**Comment by insanelydeepak** [comment]
@vit9696  i can confirm resources are ok and verifiied , for comparing result i made Patched AppleHDA using ALC CS4210 resources with no issues

**Comment by vit9696** [comment]
@insanelydeepak well, I don't know what to think of then. Clearly the resources are fed to AppleHDA according to the log (see alc @ resource-request arrived paltform part). I do see no byte patching though. My suggestions will be:
1. Redo the log patching needs to be seen.
2. Try patching AppleHDA via Clover but inject resources via AppleALC.

Could you try that with @Sexytaco?

**Comment by insanelydeepak** [comment]
Yes sure will report result

**Comment by insanelydeepak** [comment]
@vit9696 after detail result found AppleALC is unable to perform binaryPatch

**Comment by vit9696** [comment]
@insanelydeepak that sounds more like it. Otherwise it would have made no sense at all. Could you try getting the log with AppleALC patching part? It prints the details of every patch it applies in debug mode. Perhaps just need to get the gzipped system.log if it the usual system.log has none of it.

Also, could you confirm these are correct patches? Byte by byte:
```
static const uint8_t patchBuf492[] { 0x41, 0xC6, 0x06, 0x00, 0x49, 0x8B, 0xBC, 0x24, };
static const uint8_t patchBuf493[] { 0x41, 0xC6, 0x06, 0x01, 0x49, 0x8B, 0xBC, 0x24, };
static const uint8_t patchBuf494[] { 0x41, 0xC6, 0x06, 0x00, 0x48, 0x8B, 0xBB, 0x68, };
static const uint8_t patchBuf495[] { 0x41, 0xC6, 0x06, 0x01, 0x48, 0x8B, 0xBB, 0x68, };
static const uint8_t patchBuf496[] { 0x41, 0xC6, 0x86, 0x43, 0x01, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf497[] { 0x41, 0xC6, 0x86, 0x43, 0x01, 0x00, 0x00, 0x01, };
static const uint8_t patchBuf498[] { 0x06, 0x00, 0xDE, 0x10, };
static const uint8_t patchBuf499[] { 0x00, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf500[] { 0x61, 0x02, 0xEC, 0x10, };
static const uint8_t patchBuf501[] { 0x00, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf502[] { 0x62, 0x02, 0xEC, 0x10, };
static const uint8_t patchBuf503[] { 0x00, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf504[] { 0x85, 0x08, 0xEC, 0x10, };
static const uint8_t patchBuf505[] { 0x00, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf506[] { 0x83, 0x19, 0xD4, 0x11, };
static const uint8_t patchBuf507[] { 0x00, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf508[] { 0x8A, 0x19, 0xD4, 0x11, };
static const uint8_t patchBuf509[] { 0x00, 0x00, 0x00, 0x00, };
static const uint8_t patchBuf510[] { 0x84, 0x19, 0xD4, 0x11, };
static const uint8_t patchBuf511[] { 0x13, 0x42, 0x13, 0x10, };
static const KextPatch patches34[] {
	{ { &kextList[2], patchBuf492, patchBuf493, 8, 1 }, 13, 13 },
	{ { &kextList[2], patchBuf494, patchBuf495, 8, 1 }, 14, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf496, patchBuf497, 8, 1 }, 13, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf498, patchBuf499, 4, 2 }, 13, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf500, patchBuf501, 4, 2 }, 13, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf502, patchBuf503, 4, 2 }, 13, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf504, patchBuf505, 4, 2 }, 13, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf506, patchBuf507, 4, 2 }, 15, 15 },
	{ { &kextList[2], patchBuf508, patchBuf509, 4, 2 }, 16, KernelPatcher::KernelAny },
	{ { &kextList[2], patchBuf510, patchBuf511, 4, 2 }, KernelPatcher::KernelAny, KernelPatcher::KernelAny },
};
```
The order is like that: kext ref (&kextList[2] is AppleHDA), find, replace, size, number of replacements, minimal kernel version, maximum kernel version. Might there be a chance the replacement number is incorrect or the kernel version is all wrong? Or perhaps there is a typo in the bytes?

**Comment by vit9696** [comment]
A workaround does exist. If any news on how to fix this appear this could be reopened.
