### ISSUE TITLE
vt2021 now is working all right in 10.12dp3

### ISSUE THREAD

**Issue by melxman** [vit9696/AppleALC#72]
in 10.12 ,use layoutid=5 and change  8319d411 to  is not working.
but,change 8b19d411 is working all right.

8419d411 is AD1984
8B19D411 is AD1988

and someone fix mic,but i have no idea

**Comment by vit9696** [comment]
Nice to hear that you got it work. Unfortunately I did not fully understand what I need to change. Currently it is like this:
8419d411 → 41040611 Mavericks and newer
8319d411 → 00000000 El Capitan
8a19d411 → 00000000 Sierra and newer

What should we have now to get it work? Should I replace 8a19d411 patch with 8b19d411?

**Comment by melxman** [comment]
yeap,you should change this
8a19d411 → 00000000 Sierra and newer

to
8b19d411 → 00000000 Sierra and newer

it should be worked

but still has some kernl panic

**Comment by vit9696** [comment]
Alright. Last question, will vt 2021 work with this change on 10.9~10.11 as well?

**Comment by melxman** [comment]
i dont have osx above 10.11. it worked  in 10.11

**Comment by vit9696** [comment]
Committed the change. Enjoy :)
