### ISSUE TITLE
Panic on macOS Sierra PB3

### ISSUE THREAD

**Issue by faunh** [vit9696/AppleALC#73]
I'd like to start by saying thank you for your work :)

I've been getting occasional panics though. Hopefully this log is useful. This is with version 1.0.13

Anonymous UUID:       4FF6F36B-08BA-B428-A332-9A7F490CCF41

Fri Aug  5 17:43:48 2016

*** Panic Report ***
panic(cpu 0 caller 0xffffff801d710e25): "thread_invoke: preemption_level 1, possible cause: blocking while holding a spinlock, or within interrupt context"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.1.4.1.1/osfmk/kern/sched_prim.c:2077
Backtrace (CPU 0), Frame : Return Address
0xffffff9214a8b9c0 : 0xffffff801d6f84ac mach_kernel : _panic + 0xec
0xffffff9214a8ba40 : 0xffffff801d710e25 mach_kernel : _thread_unstop + 0x11f5
0xffffff9214a8bac0 : 0xffffff801d70fb8e mach_kernel : _thread_block_reason + 0xde
0xffffff9214a8bb00 : 0xffffff801d80339e mach_kernel : _lck_mtx_lock_wait_x86 + 0x1fe
0xffffff9214a8bb50 : 0xffffff801d6a70bd mach_kernel : _lck_mtx_lock + 0x28d
0xffffff9214a8bb70 : 0xffffff801dc5e14d mach_kernel : __ZN8OSSymbol11withCStringEPKc + 0x1d
0xffffff9214a8bba0 : 0xffffff801dc8c3c2 mach_kernel : __ZNK15IORegistryEntry11getPropertyEPKc + 0x12
0xffffff9214a8bbc0 : 0xffffff7fa09d0396 as.vit9696.AppleALC : __ZZN10AlcEnabler10grabCodecsEvEN3$_18__invokeEP15IORegistryEntry + 0x1e
0xffffff9214a8bbf0 : 0xffffff7fa09da2ca as.vit9696.AppleALC : __ZN6IOUtil17findEntryByPrefixEP15IORegistryEntryPKcPK15IORegistryPlanePFbS1_Eb + 0x77
0xffffff9214a8bc60 : 0xffffff7fa09cff4d as.vit9696.AppleALC : __ZN10AlcEnabler10grabCodecsEv + 0xb7
0xffffff9214a8bca0 : 0xffffff7fa09cf985 as.vit9696.AppleALC : __ZN10AlcEnabler11processKextEmym + 0x95
0xffffff9214a8bce0 : 0xffffff7fa09dad2e as.vit9696.AppleALC : __ZN13KernelPatcher22onKextSummariesUpdatedEv + 0xda
0xffffff9214a8bd20 : 0xffffff801dc4cf28 mach_kernel : __ZN6OSKext25updateLoadedKextSummariesEv + 0x4b8
0xffffff9214a8bda0 : 0xffffff801dc44694 mach_kernel : __ZN6OSKext4loadEhhP7OSArray + 0x6e4
0xffffff9214a8be10 : 0xffffff801dc51442 mach_kernel : __ZN6OSKext22loadKextWithIdentifierEP8OSStringbbhhP7OSArray + 0xf2
0xffffff9214a8be60 : 0xffffff801dcb54b0 mach_kernel : __ZNK11IOCatalogue14isModuleLoadedEP12OSDictionary + 0xe0
0xffffff9214a8be80 : 0xffffff801dc999fe mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0x2be
0xffffff9214a8bf10 : 0xffffff801dc99686 mach_kernel : __ZN9IOService14doServiceMatchEj + 0x236
0xffffff9214a8bf60 : 0xffffff801dc9b09e mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x14e
0xffffff9214a8bfb0 : 0xffffff801d6a7af7 mach_kernel : _call_continuation + 0x17
      Kernel Extensions in backtrace:
         as.vit9696.AppleALC(1.0.13)[57D6FC18-EE67-3FF5-9E8D-D2ECF694C2B4]@0xffffff7fa09ce000->0xffffff7fa0a86fff

BSD process name corresponding to current thread: kernel_task
Boot args: -alcbeta keepsyms=1 nvda_drv=1  

Mac OS version:
16A269f

Kernel version:
Darwin Kernel Version 16.0.0: Tue Jul 26 18:32:56 PDT 2016; root:xnu-3789.1.4.1.1~1/RELEASE_X86_64
Kernel UUID: B9F1E341-610E-344F-A287-A1A079D87966
Kernel slide:     0x000000001d400000
Kernel text base: 0xffffff801d600000
__HIB  text base: 0xffffff801d500000
System model name: iMac14,2 (Mac-27ADBB7B4CEE8E61)

**Comment by vit9696** [comment]
Hi, this is fixed in the upcoming 1.0.14 (https://github.com/vit9696/AppleALC/commit/9f0f10d1a659d1e261e059f8a3d36f6c6e0b7b66).
Please compile the trunk version for the time being ^_^
