### ISSUE TITLE
No audio devices - ALC 887

### ISSUE THREAD

**Issue by maxhartung** [vit9696/AppleALC#74]
Hi,

I installed macOS Sierra 10.12 and I copied your AppleALC.kext file to Clover's kext folder and the config.plist set the layout ID to 11 (this layout is working on El Capitan) and when I restarted the PC it appears that I don't have any audio devices.

On El Capitan it was working without a problem all ports just with these 2 changes: your AppleALC.kext file and layout ID 11 in config.plist.

Do you need any logs ? If yes, please tell me.

Thanks !

Mobo: Gigabyte B85M-D2V rev 1.1
CPU: Intel Pentium G3220
GPU: NVIDIA GeForce GT 210
Sound chip: Realtek ALC 887 with 3 ports on the back and 2 on the front.

**Comment by vit9696** [comment]
Check the wiki. Did you miss -alcbeta boot-arg?
