### ISSUE TITLE
VT1802 Not Working on 10.11.6

### ISSUE THREAD

**Issue by nahtnam** [vit9696/AppleALC#78]
Hey!

I installed the kext in the EFI/CLOVER/kexts/Other, and I confirmed that it was loaded before AppleHDA. I then updated my config.plist to use layout 3, but speakers, microphone, and audio jacks are all not working. I can provide any information you need.

Thanks.

**Comment by vit9696** [comment]
Hi,  
VT1802 support seems to be originating from Mirone resources. I guess we cannot do much but recommend you contact him or do your own research to get the working resources. When you have them create a new issue so that we could add them to AppleALC.  
Vit
