### ISSUE TITLE
No sound / incorrect port detection for ALC662

### ISSUE THREAD

**Issue by duksi1993** [vit9696/AppleALC#80]
Hello,
I have tried to use AppleALC kext on OS X El Capitan 10.11.6, but without success.
I have ASRock Q1900 MB (which does have Intel High Definition Audio - dev-id: 0x80860F04 with Realtek ALC662 Audio codec - dev-id: 0x10EC0662).
I've injected layout-id 5 (7 is not working - no audio devices) using Clover, and have enabled FixHDA in Clover's DSDT patches.

After OS X boot, I got my sound device and device ports recognized, but they are all messed up.
As you see in picture (attachment) - names are wrong, and there is an Optical Digital OUT (SPDIF) which my audio card doesn't have. Also, two ports from back panel are recognized as Input only, so I am unable to use 5.1 multi-channel.
Also, I got no sound on any of these ports.

What can be a problem?
Thanks anyway.

I'm attaching:

System.log (cat /var/log/system.log | grep AppleALC)

[applealc-debug.txt](https://github.com/vit9696/AppleALC/files/462245/applealc-debug.txt)

Picture mentioned above:
![applealc662](https://cloud.githubusercontent.com/assets/17316274/18359143/d1daaaa2-75f8-11e6-8051-430337bde365.jpg)

DPCI Manager Info for Audio Card:

![alc662dpci1](https://cloud.githubusercontent.com/assets/17316274/18360314/d0ad330c-75fd-11e6-8d98-9c7dd1239271.jpg)
![alc662dpci2](https://cloud.githubusercontent.com/assets/17316274/18360320/d6fa70e4-75fd-11e6-9682-154f29968612.jpg)

**Comment by vit9696** [comment]
I have a feeling you might have corrupted AppleHDA due to the names.
Otherwise you might have to ask Mirone why his resources do not work for you.

**Comment by Mirone** [comment]
You do not have a driver audio supported by AppleHDAContorller.kext, as described in this post: http://www.insanelymac.com/forum/topic/310914-applehdacontroller-native-intel-ids
you can try to replace your ID from the controller with an ID 
that is suporatdo, for example open the binary of AppleHDAContorller.kext using HexFiend and search for: 
80863B56 and replace it with your in this case: 80860F04, they 
can be reversed as in most of the cases.

**Comment by vit9696** [comment]
@Mirone Thanks for the information. AppleALC currently has a dedicated [section](https://github.com/vit9696/AppleALC/blob/master/Resources/Controllers.plist) for controller patches. I can see a patch for 0x8CA0 (Z97) controller there, and you have it listed as supported. Is that a recent addition? It is marked as 10.9+ in the plist, but maybe 10.11 (or some point update?) fixed this?

Also, I think we can add automatic patches for all the other controllers mentioned on the page. Do you have a list of _recommended_ replacements?

**Comment by vandroiy2013** [comment]
@duksi1993, Your controller added. Download sources, build kext and try it. Report with results.

**Comment by duksi1993** [comment]
I got no audio ports in Sound Perferences (Sound widget next to clock is greyed out).
Device pins are recognized same as in previous build (but there are is nothing in Devices except Vega WebCam)
![](https://cloud.githubusercontent.com/assets/17316274/18359143/d1daaaa2-75f8-11e6-8051-430337bde365.jpg)

I'm attaching new AppleALC Debug...
[applealc-debug-20160914.txt](https://github.com/vit9696/AppleALC/files/472688/applealc-debug-20160914.txt)

**Comment by vandroiy2013** [comment]
This not a debug log.

In Terminal - cat /var/log/system.log | grep AppleALC

**Comment by vit9696** [comment]
@duksi1993 read this [page](https://github.com/vit9696/AppleALC/wiki/Installation-and-usage) on how to enable debug prints.

**Comment by duksi1993** [comment]
I just saw that there is new layout-id (11) ... Maybe that's the reason I didn't get debug info.
I changed Clover config to inject that one, and I got same problem I got at the begining. I got no sound from any of detected ports.

Anyway, I have already added -alcdbg boot parameter to Clover config.plist (since I installed AppleALC for first time) and used terminal command (cat /var/log/system.log | grep AppleALC > applealc-debug-20160914-2.txt) - and got this file -> 
[applealc-debug-20160914-2.txt](https://github.com/vit9696/AppleALC/files/472732/applealc-debug-20160914-2.txt)

![applealc-20160914-2](https://cloud.githubusercontent.com/assets/17316274/18521164/5b3bb7e4-7aab-11e6-85ae-b407a23bad97.jpg)

**Comment by vit9696** [comment]
Well, according to the log the controller was successfully patched without the issues.

I could imagine trying other variants to mask to. But that's up to @Mirone probably.  
If you do not want to wait I'd suggest you try other controllers by editing Controllers.plist and replacing 563b (8086:3B56   Name: 5 Series/3400 Series Chipset High Definition Audio) by some other controller from the page. Remember that the byte order is reversed.  Report if any controller works for you…

**Comment by duksi1993** [comment]
Ok, I will try... Thanks anyway 😃

**Comment by duksi1993** [comment]
Got it working by replacing 0c0c with 0f04 (Name: Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (Haswell)

😄 

I have just one more question... While I was using VoodooHDA, I patched it to get 5.1 surround.
Is there a way, just to switch Inputs (Line-In and Internal-Mic) to be recognized as outputs (Rear and Center/Subwoofer Output)? 
I suppose I need to edit Layout-ID xml file, but I do not have experience with AppleHDA patching.

**Comment by vit9696** [comment]
That's right. I committed a change fixing the issue. Nice!

Regarding 5.1 support… it might be possible but it is out of this project area to work on something like this. Try to read about building AppleHDA chains somewhere, perhaps you could do this. In case you succeed I may imagine merging the resources into AppleALC.

**Comment by Mirone** [comment]
Great, That good that everything is working as expected. 
it is always good to be able to help.
