### ISSUE TITLE
kernel[0]: Sound assertion - 8086:a170 FIFO error (Stream 8)

### ISSUE THREAD

**Issue by Xiaoyuyexi** [vit9696/AppleALC#86]
mac os 10.11.6
asus z170-a alc892
clover fixhda audio inject 1
kernel[0]: AppleALC: (DEBUG) patcher @ last kext is <ptr> and its name is com.apple.iokit.IOSerialFamilySound assertion in AppleHDACodecGeneric at line 366

**Comment by Xiaoyuyexi** [comment]
when the log show
kernel[0]: Sound assertion - 8086:a170 FIFO error (Stream 8) 
the sound will stop working
if i pause the music, wait a monment,
play again the music,it's normal.
so? how can i to do?

**Comment by vit9696** [comment]
I see. 
Unfortunately this is not a problem with AppleALC but the resources you use and/or the hardware you have. I am sorry but I cannot really help you.
What I could imagine happening is some physical interference from some other device nearby or maybe heat. But that's just a blind thought, don't rely on it.
