### ISSUE TITLE
ALC1200 invalid

### ISSUE THREAD

**Issue by bouddhiste** [vit9696/AppleALC#87]
Audio does not play with ALC1200 on ASUS P5Q board

**Comment by vit9696** [comment]
Nobody submitted ALC1200 resources so far. Not a bug.

**Comment by vandroiy2013** [comment]
ALC1200 actually is ALC888 and this resources are working well from 10.9 till 10.11.6. Check your system.

**Comment by bouddhiste** [comment]
ALC1200 actually is ALC888 and this resources are working well from 10.9 till 10.11.6. Now  I'm suing Sierra10.12GM,ALC888 doesn't work.
