### ISSUE TITLE
ALC1200 resources

### ISSUE THREAD

**Issue by bouddhiste** [vit9696/AppleALC#89]
Please help make a AppleALC available for ALC1200

**Comment by bouddhiste** [comment]
[ALC1200_Codec.txt.zip](https://github.com/vit9696/AppleALC/files/478673/ALC1200_Codec.txt.zip)

**Comment by tanpengsccd** [comment]
is this for Asus P5Q？

**Comment by bouddhiste** [comment]
Yes. this is for Asus P5Q

**Comment by vandroiy2013** [comment]
AppleALC already have support for this codec. All three revisions are supported. I have Asus P5Q. It works well from 10.9 till 10.11.6. Don't have Sierra on this rig. You should try it on El Capitan. If it works try on Sierra with debug kext and -alcdbg in bootargs and provide log.

**Comment by bouddhiste** [comment]
yes, it works well from 10.9 till 10.11.6 and even works well on  10.12beta4 rig, but doesn’t work  on Sierra rig from Beta5 till 10.12GM

**Comment by vandroiy2013** [comment]
I'll try change masking patch for you... Later. Have work to do...

**Comment by bouddhiste** [comment]
Looking forward   thanks

**Comment by bouddhiste** [comment]
Looking forward.  thanks

**Comment by vandroiy2013** [comment]
Build new version from sources and try it. Should work... Report

**Comment by bouddhiste** [comment]
How about your new version? Can it work?

**Comment by vandroiy2013** [comment]
I have made changes. Download latest sources and build kext with xcode...

**Comment by bouddhiste** [comment]
sorry, I am a novice and don't know how to build kext with Xcode...

**Comment by vandroiy2013** [comment]
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/485341/AppleALC.kext.zip)

**Comment by vandroiy2013** [comment]
@bouddhiste , Is it working?

**Comment by vandroiy2013** [comment]
Confirmed working on P5Q. Issue closed

**Comment by bouddhiste** [comment]
sorry,I was on business days ago not to reply. now eager to know I should select which Layout ID 1,2,3,5,or7? I tried these 4id but still don't work

**Comment by vandroiy2013** [comment]
It is confirmed working! Compare all your steps with manual.

**Comment by tanpengsccd** [comment]
inject layout ID 3/5/7 all work！yes mine is ASUS P5Q too！
