### ISSUE TITLE
Unable to work for Conexant 20590 after upgrading to macOS Sierra

### ISSUE THREAD

**Issue by dante2130** [vit9696/AppleALC#92]
I use layout №3 and it works fine in El Capitan. But not working on Sierra.

**Comment by vandroiy2013** [comment]
OK. Try this version. Report.
[AppleALC.kext_CX20590Test.zip](https://github.com/vit9696/AppleALC/files/491647/AppleALC.kext_CX20590Test.zip)

**Comment by dante2130** [comment]
Don't working(

**Comment by vandroiy2013** [comment]
Hm... It should work... Try this
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/491726/AppleALC.kext.zip)

**Comment by dante2130** [comment]
Everything works, but without mic. He shows in devices but don't worked.

**Comment by vandroiy2013** [comment]
Sorry, can't help with this... Try another layout-id (3, 12 or 28) If you use layout-id 3 try to ask @Mirone for help

**Comment by dante2130** [comment]
Ok, thanks for the help :)
