### ISSUE TITLE
ALC888S

### ISSUE THREAD

**Issue by vaclav-dort** [vit9696/AppleALC#94]
Hello,
please add attached ALC888S codec.

Thanks for your great work!

Best
Vaclav
[ALC888S.zip](https://github.com/vit9696/AppleALC/files/494254/ALC888S.zip)

**Comment by vandroiy2013** [comment]
ALC888/ALC1200 already present in project...

**Comment by vaclav-dort** [comment]
But not with this CodecID and without it, not function. If you have some other way place this CodecID in regular ALC888 resource, please do it.


<key>CodecID</key>
<integer>7200</integer>


Best

Vaclav

**Comment by vandroiy2013** [comment]
Give me terminal output with this command and info.plist file it creates on desktop.
[Codec-Info.command.zip](https://github.com/vit9696/AppleALC/files/495067/Codec-Info.command.zip)

**Comment by vaclav-dort** [comment]
Ok, but tonight, when I at home.

This is from Shuttle XPC.


Best

Vaclav

**Comment by vaclav-dort** [comment]
Where is output file.

Thank you very much.

I have some other problem on BRIX. I send you tomorrow this file, too.

**Comment by vaclav-dort** [comment]
Hello,

please, add this sound ALC892 from this board http://www.gigabyte.com/Motherboard/GA-Z170X-Ultra-Gaming-rev-10#sp



Best


Vaclav Dort

**Comment by vandroiy2013** [comment]
ALC892 was added almost a year ago https://github.com/vit9696/AppleALC/tree/master/Resources/ALC892

**Comment by vaclav-dort** [comment]
Sorry, but doesn't function. Nothing on sound control panel. On other oldest boards is AppleAlc ok.


Best

Vaclav

**Comment by vaclav-dort** [comment]
Sorry,

my fault, everything is OK.

best

Vaclav
