### ISSUE TITLE
ALC233 after apgrade to 10.12 no input devices

### ISSUE THREAD

**Issue by SquallATF** [vit9696/AppleALC#95]
In 10.11 my codec support modified from layout 3 and get bouth input/output worked. but after upgrade to 10.12 only output work, I have rebuild AppALC use latest code with old support file, I looked up all day but did not known what I missed.
pin config I used
```
01271C40 01271D01 01271EA6 01271F90
01A71C30 01A71D50 01A71E81 01A71F03
01471C10 01471D01 01471E17 01471F90 01470C02
02171C20 02171D10 02171E21 02171F03 02170C02
```
[my codec](https://github.com/vit9696/AppleALC/files/504366/codec1.txt)
[layout16.xml.txt](https://github.com/vit9696/AppleALC/files/504371/layout16.xml.txt)
[Platforms16.xml.txt](https://github.com/vit9696/AppleALC/files/504372/Platforms16.xml.txt)

**Comment by vit9696** [comment]
I do not think I could be of any help here. The only 10.12 change I am aware is nulling 8A19D411 if you mask for ADI1984B. There were several additions for ALC233 by @insanelydeepak, maybe you could ask him if the existing layouts are not working.

**Comment by insanelydeepak** [comment]
hello @vit9696 

> The only 10.12 change I am aware is nulling 8A19D411 if you mask for ADI1984B. 
for this codec only 1984 patch is required 

@SquallATF  did you tried Layout13 ??

**Comment by SquallATF** [comment]
layout 13 work for me, thaks @insanelydeepak @vit9696 , here is the final config for my codec for SONY VAIO Fit 14E(SVF14316SCW)
pin config
```
ASccQAEnHQEBJx6mAScfkAGnHDABpx1QAacegQGnHwMBRxwQAUcdAQFHHhcBRx+QAUcMAgIXHCACFx0QAhceIQIXHwMCFwwC
```
[ALC233.zip](https://github.com/vit9696/AppleALC/files/504770/ALC233.zip)

**Comment by vit9696** [comment]
@vandroiy2013 could this pin configuration be added to some layout then?

**Comment by insanelydeepak** [comment]
I think if @SquallATF has all input/output working with layout 13 then not required

**Comment by SquallATF** [comment]
default layout 13 can see device but no audio/voice , after modify MuteGPIO and PathMaps it works~

**Comment by insanelydeepak** [comment]
Yeah mathmap is required to initiate inputs, sometine output 
Now its @vandroiy2013 turn

**Comment by vandroiy2013** [comment]
@SquallATF Added layout-id 27. Try it. Report

**Comment by SquallATF** [comment]
@vandroiy2013 only line-in(Ext Mic) not work, I link line-out to line-in no input level. But I think it does not matter because I did not have input equipment.
