### ISSUE TITLE
No audio sound - Realtek ALC888S-VD

### ISSUE THREAD

**Issue by Jenny21David** [vit9696/AppleALC#97]
Hi Guys,

First of all, well done to Mirone, Toleda, vit9696 and all those who have contributed to come up with AppleALC.kext.

My laptop has Realtek ALC888S-VD. I had followed your instructions on how to install AppleALC (1.0.17.RELEASE) with native AppleHDA.kext. After the reboot, though my audio ports are detected, but there's no sound being produced from my internal speaker. I had also noticed that my headphone is not detected when I plug it into the HeadPhone jack (black-left). I am using layout 3 as described in WIKI for my audio codec and attached is my codec_dump.txt for your reference. 

Though I am not an expert, I tried to get my pin configurations and their respective pathmaps to compare with your AppleALC. Well, as expected, my pin configurations and pathmaps are different from the one present in AppleALC.kext for ALC888. I had also noticed that there's no node 0x15 being defined in that kext for ALC888 - layout 3 (no wonder headphone was not detected). Of course, I could be wrong :)

Appreciate your help on this as I am not sure what else I can do to get my audio working.

Thank you in advance.

~Jenny~

![screen shot 2016-10-27 at 3 28 45 am]
(https://cloud.githubusercontent.com/assets/23084817/19742276/dfdf4a1c-9bf6-11e6-914f-10791e8ab688.png)
[codec_dump.txt](https://github.com/vit9696/AppleALC/files/554284/codec_dump.txt)

**Comment by vandroiy2013** [comment]
There is only layout-id 4 for Laptop ALC888. Read the WiKi carefully)))

**Comment by Jenny21David** [comment]
Actually, I have tried layout id 1 until 4, but end up with the same result... No sound :(

**Comment by vandroiy2013** [comment]
If you provide working for you kext, i'll add support for your laptop...

**Comment by Jenny21David** [comment]
Here you go.... again, I could be wrong.


![screen shot 2016-10-27 at 4 59 00 am](https://cloud.githubusercontent.com/assets/23084817/19745032/8f32d2d0-9c02-11e6-871b-a81f3f39ff08.png)
![Uploading Screen Shot 2016-10-27 at 4.54.50 AM.png…]()

**Comment by vandroiy2013** [comment]
I asked a kext or at least resources from it... I need layout.xml.zlib and platforms.xml.zlib.

**Comment by Jenny21David** [comment]
LOL... if I have those two, I could have used them and rebuild my own AppleALC using Xcode. Instead of me seeking for help, it started to sound like as if you are requesting help from me.... :)

Anyway, I haven't created my own layout.xml.zlib and platforms.xml.zlib to test my kext yet.

**Comment by vandroiy2013** [comment]
Obviously your codec have different node sequence. I can't help you with this without working resources. Ask somebody on Insanelymac.com to help you with this.

**Comment by Jenny21David** [comment]
thanks

**Comment by Jenny21David** [comment]
Hmmm.... Appreciate if you guys can provide support for my codec. Well, I guess I have to build my own kext then. Anyway, thanks for your prompt responses.
