### ISSUE TITLE
CA0132 Gigabyte z170x Gaming 7 no sound but is showing audio control 

### ISSUE THREAD

**Issue by AppleMike** [vit9696/AppleALC#98]
Hello,

I just want to know how make the sound works. I have tried different ld layout (9,...,12) but sound doesn't work. With id 12 and 11 I get audio controls, but not sound output from any MB outputs.

With El Capitan I had sound output and volumen control. Full functionality.

Any suggestions?

Thanks a lot

**Comment by vandroiy2013** [comment]
Try build new kext. Probably it was fixed in this commit https://github.com/vit9696/AppleALC/commit/f4e9d554b7e5d12047f911570319ddd8539f261f

**Comment by AppleMike** [comment]
Hi @vandroiy2013 

I don't know how to build kexts, I have put the new lines from f4e9d55 but not changes...

Won't I have any solution to get sound in Sierra?

**Comment by vandroiy2013** [comment]
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/571290/AppleALC.kext.zip)

Here is prebuild binary...

**Comment by AppleMike** [comment]
Hi again @vandroiy2013 

Yes it works..!!!  id 9 and 10.

But unfortunately only line sound without volumen controls, no headphones.

Do you think that is possible to get volumen control?


thanks a lot... ;)

**Comment by vandroiy2013** [comment]
I don't know))) Ask this question on InsanelyMac http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/
