### ISSUE TITLE
ALC282 Not working

### ISSUE THREAD

**Issue by Generation88** [vit9696/AppleALC#99]
i have dell inspiron 3521 ALC282 with layout ID 28 & speakers & microphone & line in are not working & hdmi audio also...was working earlier on yosemite with different kexts

**Comment by Generation88** [comment]
here is the info you requested on y

**Comment by vit9696** [comment]
I think you need to contact the people who are good at resource making, maybe check #100 for a hint?

**Comment by vit9696** [comment]
It is starting to mislead the project goals by posting resource issues without the solutions on github. Here we do not help to explore code dumps and are not interested in them. Please avoid creating issues unless you have working resources.
For the aforementioned reason all the unlrelated issues are closed.
